# Exercício 3.4

In [5]:
%pip install numpy
from simplex import simplex
import numpy as np
from fractions import Fraction

solution_types = {
    -1: 'Unfeasible',
    1: 'Optimal finite solution found',
    2: 'Multiple optimal solutions found',
    3: 'Unbounded'
}

A = np.array([
    [2, 3, 0, 0],
    [1,-2, 0, 1],
])
b = np.array([
    6,
    0
])
c = np.array([
    -2,
     1,
     0,
     0,
])
I = [1, 3]
Z_star, x_star, I_star, iterations, solution_type = simplex(A, b, c, I, debug = True)
result_repr = f'''
Exercício 3.4:

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)


--------------------------------------------------------------------------------
Solution for:

min cᵀx
subject to:
Ax = b

where 

c=[-2  1  0  0],
x=['x_0' 'x_1' 'x_2' 'x_3'],
A=
[[ 2  3  0  0]
 [ 1 -2  0  1]],
b=
[[6]
 [0]]


After Iteration 1:
Basic variables indices before: [1 3]
Non-basic variables indices before: [0 2]
Basic variables indices after: [1, 0]
Non-basic variables indices after: [3, 2]
x_I = [2. 4.]
A_I =
[[ 3  0]
 [-2  1]]
A_I^-1 =
[[0.33333333 0.        ]
 [0.66666667 1.        ]]
A_J =
[[2 0]
 [1 0]]
π = [0.33333333 0.        ]
z_0 = 2.0
c_hat_J = [2.66666667 0.        ]
y_k = [0.66666667 2.33333333]
Variable to enter the basis: x_0
Variable to leave the basis: x_3

After Iteration 2:
Basic variables indices before: [1 0]
Non-basic variables indices before: [3 2]
Basic variables indices after: [1, 0]
Non-basic variables indices after: [3, 2]
x_I = [0.85714286 1.71428571]
A_I =
[[ 3  2]
 [-2  1]]
A_I^-1 =
[[ 0.14285714 -0.28571429]
 [ 0.28571429  0.42857143]]
A_J 