# Exercício 3.3

In [4]:
%pip install numpy
from simplex import simplex
import numpy as np
from fractions import Fraction

solution_types = {
    -1: 'Unfeasible',
    1: 'Optimal finite solution found',
    2: 'Multiple optimal solutions found',
    3: 'Unbounded'
}

## letra a)

In [14]:
# resolução do sistema de equações lineares obtido pela solução gráfica do ponto de máximo
A = np.array([
    [-2, 1],
    [5, 3]
])
B = np.array([
    [4],
    [15]
])
x_star = np.linalg.solve(A,B).ravel()
fraction = lambda x: str(Fraction(str(x)).limit_denominator())
display(
    list(
        map(fraction, x_star)
    )
)

['3/11', '50/11']

## letra b)

In [15]:
A = np.array([
    [ 1,-2, 1, 0, 0],
    [-2, 1, 0, 1, 0],
    [ 5, 3, 0, 0, 1]
])
b = np.array([
    0,
    4,
    15
])
c = np.array([
    -1,
    -3,
     0,
     0,
     0
])
I = [2, 3, 4]
Z_star, x_star, I_star, iterations, solution_type = simplex(A, b, c, I, debug = True)
result_repr = f'''
Exercício 3:

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)


--------------------------------------------------------------------------------
Solution for:

min cᵀx
subject to:
Ax = b

where 

c=[-1 -3  0  0  0],
x=['x_0' 'x_1' 'x_2' 'x_3' 'x_4'],
A=
[[ 1 -2  1  0  0]
 [-2  1  0  1  0]
 [ 5  3  0  0  1]],
b=
[[ 0]
 [ 4]
 [15]]


After Iteration 1:
Basic variables indices before: [2 3 4]
Non-basic variables indices before: [0 1]
Basic variables indices after: [2, 1, 4]
Non-basic variables indices after: [0, 3]
x_I = [ 0.  4. 15.]
A_I =
[[1 0 0]
 [0 1 0]
 [0 0 1]]
A_I^-1 =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A_J =
[[ 1 -2]
 [-2  1]
 [ 5  3]]
π = [0. 0. 0.]
z_0 = 0.0
c_hat_J = [1. 3.]
y_k = [-2.  1.  3.]
Variable to enter the basis: x_1
Variable to leave the basis: x_3

After Iteration 2:
Basic variables indices before: [2 1 4]
Non-basic variables indices before: [0 3]
Basic variables indices after: [2, 1, 0]
Non-basic variables indices after: [4, 3]
x_I = [8. 4. 3.]
A_I =
[[ 1 -2  0]
 [ 0  1  0]
 [ 0  3  1]]
A_I^-1 =
[[ 1.  2.  0.]
 [ 0.  1.  0.

In [16]:
Fraction(Z_star).limit_denominator()

Fraction(-153, 11)