In [1]:
%pip install numpy
import simplex
import numpy as np

solution_types = {
    -1: 'Unfeasible',
    1: 'Optimal finite solution found',
    2: 'Multiple optimal solutions found',
    3: 'Unbounded'
}

# Letra a)

In [ ]:
A = np.array([
    [2, 3, 1, 0, 0],
    [2, 1, 0, 1, 0],
    [3, 3, 0, 0, 1]
])
b = np.array([
    18,
    12,
    24
])
c = np.array([
    -5,
    -6,
    0,
    0,
    0
])
I = [2, 3, 4]
Z_star, x_star, I_star, iterations, solution_type = simplex.simplex(A, b, c, I, debug = True)
result_repr = f'''
Letra a):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)

# Letra b)

In [ ]:
A = np.array([
    [2, 1, 5, 6, 1, 0, 0],
    [3, 1, 3, 1, 0, 1, 0],
    [7, 0, 0, 1, 0, 0, 1]
])
b = np.array([
    20,
    24,
    70
])
c = np.array([
    -15,
    -6,
    -9,
    -2,
    0,
    0,
    0
])
I = [4, 5, 6]
Z_star, x_star, I_star, iterations, solution_type = simplex.simplex(A, b, c, I, debug = True)
result_repr = f'''
Letra b):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)

# Letra c)

In [2]:
A = np.array([
    [1, 3, 1, 0, 0, 0],
    [2, 2, 0, 1, 0, 0],
    [1, 1, 0, 0, 1, 0],
    [0, 1, 0, 0, 0, 1]
])
b = np.array([
    7,
    8,
    3,
    2
])
c = np.array([
    -4,
    -3,
    0,
    0,
    0,
    0
])
I = [2, 3, 4, 5]
Z_star, x_star, I_star, iterations, solution_type = simplex.simplex(A, b, c, I, debug = True)
result_repr = f'''
Letra c):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)


--------------------------------------------------------------------------------
Solution for:

min cᵀx
subject to:
Ax = b

where 

c=[-4 -3  0  0  0  0],
x=['x_0' 'x_1' 'x_2' 'x_3' 'x_4' 'x_5'],
A=
[[1 3 1 0 0 0]
 [2 2 0 1 0 0]
 [1 1 0 0 1 0]
 [0 1 0 0 0 1]],
b=
[[7]
 [8]
 [3]
 [2]]


After Iteration 1:
Basic variables indices before: [2 3 4 5]
Non-basic variables indices before: [0 1]
Basic variables indices after: [2, 3, 0, 5]
Non-basic variables indices after: [4, 1]
x_I = [7. 8. 3. 2.]
A_I =
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
A_I^-1 =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
A_J =
[[1 3]
 [2 2]
 [1 1]
 [0 1]]
π = [0. 0. 0. 0.]
z_0 = 0.0
c_hat_J = [4. 3.]
y_k = [1. 2. 1. 0.]
Variable to enter the basis: x_0
Variable to leave the basis: x_4

After Iteration 2:
Basic variables indices before: [2 3 0 5]
Non-basic variables indices before: [4 1]
Basic variables indices after: [2, 3, 0, 5]
Non-basic variables indices after: [4, 1]
x_I = [4. 2. 3. 2.]
A_I =

# Letra d)

In [4]:
A = np.array([
    [3, 1, 1, 1, 0, 0],
    [1,-1, 2, 0, 1, 0],
    [1, 1,-1, 0, 0, 1],
])
b = np.array([
    60,
    10,
    20
])
c = np.array([
    -2,
    1,
    -1,
    0,
    0,
    0
])
I = [3, 4, 5]
Z_star, x_star, I_star, iterations, solution_type = simplex.simplex(A, b, c, I, debug = True)
result_repr = f'''
Letra d):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)


--------------------------------------------------------------------------------
Solution for:

min cᵀx
subject to:
Ax = b

where 

c=[-2  1 -1  0  0  0],
x=['x_0' 'x_1' 'x_2' 'x_3' 'x_4' 'x_5'],
A=
[[ 3  1  1  1  0  0]
 [ 1 -1  2  0  1  0]
 [ 1  1 -1  0  0  1]],
b=
[[60]
 [10]
 [20]]


After Iteration 1:
Basic variables indices before: [3 4 5]
Non-basic variables indices before: [0 1 2]
Basic variables indices after: [3, 0, 5]
Non-basic variables indices after: [4, 1, 2]
x_I = [60. 10. 20.]
A_I =
[[1 0 0]
 [0 1 0]
 [0 0 1]]
A_I^-1 =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A_J =
[[ 3  1  1]
 [ 1 -1  2]
 [ 1  1 -1]]
π = [0. 0. 0.]
z_0 = 0.0
c_hat_J = [ 2. -1.  1.]
y_k = [3. 1. 1.]
Variable to enter the basis: x_0
Variable to leave the basis: x_4

After Iteration 2:
Basic variables indices before: [3 0 5]
Non-basic variables indices before: [4 1 2]
Basic variables indices after: [3, 0, 1]
Non-basic variables indices after: [4, 5, 2]
x_I = [30. 10. 10.]
A_I =
[[1 3 0]
 [0 1 0]
 [0 1 1]]
A_I

# Letra e)

In [5]:
A = np.array([
    [2, 3, 1, 1, 0, 0],
    [4, 2, 2, 0, 1, 0],
    [3, 2, 2, 0, 0, 1],
])
b = np.array([
     5,
    11,
     8
])
c = np.array([
    -5,
    -4,
    -3,
     0,
     0,
     0
])
I = [3, 4, 5]
Z_star, x_star, I_star, iterations, solution_type = simplex.simplex(A, b, c, I, debug = True)
result_repr = f'''
Letra e):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)


--------------------------------------------------------------------------------
Solution for:

min cᵀx
subject to:
Ax = b

where 

c=[-5 -4 -3  0  0  0],
x=['x_0' 'x_1' 'x_2' 'x_3' 'x_4' 'x_5'],
A=
[[2 3 1 1 0 0]
 [4 2 2 0 1 0]
 [3 2 2 0 0 1]],
b=
[[ 5]
 [11]
 [ 8]]


After Iteration 1:
Basic variables indices before: [3 4 5]
Non-basic variables indices before: [0 1 2]
Basic variables indices after: [0, 4, 5]
Non-basic variables indices after: [3, 1, 2]
x_I = [ 5. 11.  8.]
A_I =
[[1 0 0]
 [0 1 0]
 [0 0 1]]
A_I^-1 =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A_J =
[[2 3 1]
 [4 2 2]
 [3 2 2]]
π = [0. 0. 0.]
z_0 = 0.0
c_hat_J = [5. 4. 3.]
y_k = [2. 4. 3.]
Variable to enter the basis: x_0
Variable to leave the basis: x_3

After Iteration 2:
Basic variables indices before: [0 4 5]
Non-basic variables indices before: [3 1 2]
Basic variables indices after: [0, 4, 2]
Non-basic variables indices after: [3, 1, 5]
x_I = [2.5 1.  0.5]
A_I =
[[2 0 0]
 [4 1 0]
 [3 0 1]]
A_I^-1 =
[[ 0.5  0.   0. ]
 [-2. 