# Exercício 3.4

In [1]:
%pip install numpy
from simplex import simplex
import numpy as np
from fractions import Fraction

solution_types = {
    -1: 'Unfeasible',
    1: 'Optimal finite solution found',
    2: 'Multiple optimal solutions found',
    3: 'Unbounded'
}

A = np.array([
    [ 3,-3, 2, 1, 0],
    [-1, 2, 1, 0, 1],
])
b = np.array([
    3,
    6
])
c = np.array([
    -3,
    -2,
    -1,
     0,
     0
])
I = [3, 4]
Z_star, x_star, I_star, iterations, solution_type = simplex(A, b, c, I, debug = True)
result_repr = f'''
Exercício 3.4:

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)


--------------------------------------------------------------------------------
Solution for:

min cᵀx
subject to:
Ax = b

where 

c=[-3 -2 -1  0  0],
x=['x_0' 'x_1' 'x_2' 'x_3' 'x_4'],
A=
[[ 3 -3  2  1  0]
 [-1  2  1  0  1]],
b=
[[3]
 [6]]


After Iteration 1:
Basic variables indices before: [3 4]
Non-basic variables indices before: [0 1 2]
Basic variables indices after: [0, 4]
Non-basic variables indices after: [3, 1, 2]
x_I = [3. 6.]
A_I =
[[1 0]
 [0 1]]
A_I^-1 =
[[1. 0.]
 [0. 1.]]
A_J =
[[ 3 -3  2]
 [-1  2  1]]
π = [0. 0.]
z_0 = 0.0
c_hat_J = [3. 2. 1.]
y_k = [ 3. -1.]
Variable to enter the basis: x_0
Variable to leave the basis: x_3

After Iteration 2:
Basic variables indices before: [0 4]
Non-basic variables indices before: [3 1 2]
Basic variables indices after: [0, 1]
Non-basic variables indices after: [3, 4, 2]
x_I = [1. 7.]
A_I =
[[ 3  0]
 [-1  1]]
A_I^-1 =
[[0.33333333 0.        ]
 [0.33333333 1.        ]]
A_J =
[[ 1 -3  2]
 [ 0  2  1]]
π = [-1.  0.]
z_0 = -3.0
c_hat_J = [-