In [1]:
%pip install numpy
import simplex
import numpy as np

solution_types = {
    -1: 'Unfeasible',
    1: 'Optimal finite solution found',
    2: 'Multiple optimal solutions found',
    3: 'Unbounded'
}

# Letra a)

In [ ]:
# letra a
A = np.array([
    [2, 3, 1, 0, 0],
    [2, 1, 0, 1, 0],
    [3, 3, 0, 0, 1]
])
b = np.array([
    18,
    12,
    24
])
c = np.array([
    -5,
    -6,
    0,
    0,
    0
])
I = [2, 3, 4]
Z_star, x_star, I_star, iterations, solution_type = simplex.simplex(A, b, c, I, debug = True)
result_repr = f'''
Letra a):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)

# Letra b)

In [ ]:
# letra b
A = np.array([
    [1, 3, 1, 0, 0, 0],
    [2, 2, 0, 1, 0, 0],
    [1,-1, 0, 0, 1, 0],
    [0, 1, 0, 0, 0, 1]
])
b = np.array([
    7,
    8,
    -3,
    2
])
c = np.array([
    4,
    -2,
    0,
    0,
    0,
    0
])
I = [2, 3, 4, 5]
Z_star, x_star, I_star, iterations, solution_type = simplex.simplex(A, b, c, I, debug = True)
result_repr = f'''
Letra b):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)

# Letra c)

In [ ]:
# letra c
A = np.array([
    [-1, -1, 1, 0, 0],
    [-1,  1, 0, 1, 0],
    [ 1,  2, 0, 0, 1]
])
b = np.array([
    -3,
    -1,
    4
])
c = np.array([
    -1,
    -3,
    0,
    0,
    0
])
I = [2, 3, 4]
Z_star, x_star, I_star, iterations, solution_type = simplex.simplex(A, b, c, I, debug = True)
result_repr = f'''
Letra c):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)

# Letra d)

In [2]:
# letra d
A = np.array([
    [2, 3, -3, 1, 0],
    [4, 2, -2, 0, 1],
])
b = np.array([
     6,
    -8
])
c = np.array([
     1,
     5,
    -5,
     0,
     0
])
I = [3, 4]
Z_star, x_star, I_star, iterations, solution_type = simplex.simplex(A, b, c, I, debug = True)
result_repr = f'''
Letra d):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)


--------------------------------------------------------------------------------
Solution for:

min cᵀx
subject to:
Ax = b

where 

c=[ 1  5 -5  0  0],
x=['x_0' 'x_1' 'x_2' 'x_3' 'x_4'],
A=
[[ 2  3 -3  1  0]
 [ 4  2 -2  0  1]],
b=
[[ 6]
 [-8]]


After Iteration 1:
Basic variables indices before: [3 4]
Non-basic variables indices before: [0 1 2]
Basic variables indices after: [3, 4]
Non-basic variables indices after: [0, 1, 2]
x_I = [ 6. -8.]
A_I =
[[1 0]
 [0 1]]
A_I^-1 =
[[1. 0.]
 [0. 1.]]
A_J =
[[ 2  3 -3]
 [ 4  2 -2]]
π = [0. 0.]
z_0 = 0.0
c_hat_J = [-1. -5.  5.]
Variable to enter the basis: x_2
Variable to leave the basis: x_None


Letra d):

Z_star = 0.0
x_star = [ 0.  0.  0.  6. -8.]
I_star = [3, 4]
iterations = 1
solution_type = 3 - Unbounded

