# Exercício 3

In [2]:
%pip install numpy
from simplex import simplex
import numpy as np

solution_types = {
    -1: 'Unfeasible',
    1: 'Optimal finite solution found',
    2: 'Multiple optimal solutions found',
    3: 'Unbounded'
}

A = np.array([
    [1, 7, 4, 1, 0, 0],
    [2, 1, 7, 0, 1, 0],
    [8, 4, 1, 0, 0, 1]
])
b = np.array([
    200,
    100,
    120
])
c = np.array([
    -4,
    -4,
    -7,
     0,
     0,
     0
])
I = [3, 4, 5]
Z_star, x_star, I_star, iterations, solution_type = simplex(A, b, c, I, debug = True)
result_repr = f'''
Exercício 3:

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)


--------------------------------------------------------------------------------
Solution for:

min cᵀx
subject to:
Ax = b

where 

c=[-4 -4 -7  0  0  0],
x=['x_0' 'x_1' 'x_2' 'x_3' 'x_4' 'x_5'],
A=
[[1 7 4 1 0 0]
 [2 1 7 0 1 0]
 [8 4 1 0 0 1]],
b=
[[200]
 [100]
 [120]]


After Iteration 1:
Basic variables indices before: [3 4 5]
Non-basic variables indices before: [0 1 2]
Basic variables indices after: [3, 2, 5]
Non-basic variables indices after: [0, 1, 4]
x_I = [200. 100. 120.]
A_I =
[[1 0 0]
 [0 1 0]
 [0 0 1]]
A_I^-1 =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A_J =
[[1 7 4]
 [2 1 7]
 [8 4 1]]
π = [0. 0. 0.]
z_0 = 0.0
c_hat_J = [4. 4. 7.]
y_k = [4. 7. 1.]
Variable to enter the basis: x_2
Variable to leave the basis: x_4

After Iteration 2:
Basic variables indices before: [3 2 5]
Non-basic variables indices before: [0 1 4]
Basic variables indices after: [1, 2, 5]
Non-basic variables indices after: [0, 3, 4]
x_I = [142.85714286  14.28571429 105.71428571]
A_I =
[[1 4 0]
 [0 7 0]
 [0 1 1]]
