In [2]:
%pip install numpy
%pip install sympy
%load_ext autoreload
%autoreload 2
from simplex_two_phases import simplex as simplex_two_phases
from simplex_tableau import simplex as simplex_tableau
from simplex_tableau import markdown_repr_T
from simplex import simplex
    
import numpy as np
from pprint import pprint
from IPython.display import Markdown, display

solution_types = {
    -1: 'Unfeasible',
    1: 'Optimal finite solution found',
    2: 'Multiple optimal solutions found',
    3: 'Unbounded'
}

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Lista 5
## Exercício 3.22

In [ ]:
# Instantiate the data for the default minimization
# problem in the form:
# z = min C.T @ X
# subject to:
#     A @ X = B

C = np.array([
    -3,
    -4,
    -2.5,
    0,
    0,
    0
])

A = np.array([
    [3, 4, 2, 1, 0, 0],
    [2, 1, 2, 0, 1, 0],
    [1, 3, 3, 0, 0, 1]
])

B = np.array([
    500,
    400,
    300
])

m, n = A.shape
I = [3, 4, 5]

Z_star, x_I, I_star, A_I, A, iterations, solution_type, debug_info = simplex_two_phases(A, B, C, I, debug = True)
#Z_star, x_star, I_star, iterations, solution_type = simplex(A, b, c, I, debug = True)
x_star = np.zeros(n)
x_star[I_star] = x_I
result_repr = f'''
Exercicio 3.22):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations + 1}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)
display('Simplex Steps:\n\n')
display(debug_info)

## Exercício 3.23

In [ ]:
# Instantiate the data for the default minimization
# problem in the form:
# z = min C.T @ X
# subject to:
#     A @ X = B

np.set_printoptions(suppress=True)

C = np.array([
    -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
])

A = np.array([
       [ 1.0e+00,  0.0e+00, -1.0e+00,  0.0e+00,  1.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 1.0e+00,  0.0e+00,  0.0e+00, -1.0e+00,  0.0e+00,  1.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  3.0e+01,  4.5e+03,  0.0e+00,  0.0e+00,  0.0e+00,
         1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  4.0e+01,  5.0e+03,  5.0e+03,  0.0e+00,  0.0e+00,
         0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  5.0e-01,  1.5e+02,  1.5e+02,  0.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00, -1.0e+00,  0.0e+00],
       [ 0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  1.0e+00]
])

B = np.array([
    0,
    0,
    150e3,
    100e3,
    600,
    600,
    800
])

m, n = A.shape
I = list(range(4,11))

Z_star, x_I, I_star, A_I, A, iterations, solution_type, debug_info = simplex_two_phases(A, B, C, I, debug = True)
#Z_star, x_star, I_star, iterations, solution_type = simplex(A, b, c, I, debug = True)
x_star = np.zeros(n)
x_star[I_star] = x_I
x_star = {
    f'x_{i:}': f'{x:.2f}' for i, x in enumerate(x_star)
}
result_repr = f'''
Exercicio 3.23):

Z_star = {Z_star}
x_star = {str(x_star)}
I_star = {I_star}
iterations = {iterations + 1}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)
display('Simplex Steps:\n\n')
display(debug_info)

### Estudo dos valores do vetor X nas 2 Únicas Iterações da Fase 1 do Simplex para o Problema em Tela

In [ ]:
X = list(debug_info['first phase']['first_phase_debug_info'][f'debug_info_iteration_{i:02d}']['x'] for i in range(2))
for x in X:
    display(x)

### Estudo dos valores do vetor X nas 4 Únicas Iterações da Fase 2 do Simplex para o Problema em Tela

In [ ]:
X = list(debug_info['second phase'][f'debug_info_iteration_{i:02d}']['x'] for i in range(4))
for x in X:
    display(x)

### Estudo dos valores do vetor I nas 4 Únicas Iterações da Fase 2 do Simplex para o Problema em Tela

In [ ]:
I = list(debug_info['second phase'][f'debug_info_iteration_{i:02d}']['computed I'] for i in range(4))
for i in I:
    display(i)

## Exercício 3.26

In [31]:
C = np.array([2, -2, -1, 1, 0, 0, 0, 0])
A = np.array([
    [-1,  1,  3, -3, 1, 0, 0, 0],
    [-2, 2, -1,  1, 0, 1, 0, 0],
    [2, -2,  3, -3, 0, 0, 1, 0],
    [3, -3, -2,  2, 0, 0, 0, 1]
])
B = np.array([3, 2, 6, 6])

m, n = A.shape
I = list(range(4,8))

solution = simplex_tableau(A, B, C, I)

'''
    Display solution
'''
Z_star = solution['Z_star']
I_star = solution['I_star']
X_star = np.zeros(n)
X_star[I_star] = solution['X_star']
solution_type = solution_types[
    solution['solution_type']
]
solution_md = f'''
## Solution

\\\\(X^{{*}}\\\\) = {repr(np.round(X_star, 2))}

\\\\(Z^{{*}} = {repr(np.round(Z_star, 5))} \\\\)

\\\\(\\text{{I}}^{{*}}\\\\) = {repr([
    '\\(X_' + str(i) + '\\)' for i in I_star
])}
'''
display(
    Markdown(
        solution_md
    )
)

'''
    Display Tableaus
'''
tableau_steps = solution['tableaus']
tableau_md = markdown_repr_T(tableau_steps)
display(
    Markdown(
        tableau_md
    )
)



## Solution

\\(X^{*}\\) = array([ 0.  ,  1.29,  0.57,  0.  ,  0.  ,  0.  ,  6.86, 11.  ])

\\(Z^{*} = -3.14286 \\)

\\(\text{I}^{*}\\) = ['\\(X_2\\)', '\\(X_1\\)', '\\(X_6\\)', '\\(X_7\\)']




## Iteration 1

Previous Tableau:

|   |\\(X_0\\) | \\(X_1\\) | \\(X_2\\) | \\(X_3\\) | \\(X_4\\) | \\(X_5\\) | \\(X_6\\) | \\(X_7\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | -2.000 | 2.000 | 1.000 | -1.000 | 0.000 | 0.000 | 0.000 | 0.000 | 0.000 |
| \\(X_4\\) | -1.000 | 1.000 | 3.000 | -3.000 | 1.000 | 0.000 | 0.000 | 0.000 | 3.000 |
| \\(X_5\\) | -2.000 | 2.000 | -1.000 | 1.000 | 0.000 | 1.000 | 0.000 | 0.000 | 2.000 |
| \\(X_6\\) | 2.000 | -2.000 | 3.000 | -3.000 | 0.000 | 0.000 | 1.000 | 0.000 | 6.000 |
| \\(X_7\\) | 3.000 | -3.000 | -2.000 | 2.000 | 0.000 | 0.000 | 0.000 | 1.000 | 6.000 |
### Pivot Operations

Variable to enter: \\(X_1\\)
Variable to leave: \\(X_5\\)
#### Row Operations:

1. \\(R_{X_5} = \frac{R_{X_5}}{2.0}\\)
1. \\(R_{C} = R_{C} - 2.0R_{X_5}\\)
2. \\(R_{X_4} = R_{X_4} - 1.0R_{X_5}\\)
3. \\(R_{X_6} = R_{X_6} + 2.0R_{X_5}\\)
4. \\(R_{X_7} = R_{X_7} + 3.0R_{X_5}\\)


Computed Tableau:

|   |\\(X_0\\) | \\(X_1\\) | \\(X_2\\) | \\(X_3\\) | \\(X_4\\) | \\(X_5\\) | \\(X_6\\) | \\(X_7\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | -1.000 | 0.000 | 0.000 | -2.000 |
| \\(X_4\\) | 0.000 | 0.000 | 3.500 | -3.500 | 1.000 | -0.500 | 0.000 | 0.000 | 2.000 |
| \\(X_1\\) | -1.000 | 1.000 | -0.500 | 0.500 | 0.000 | 0.500 | 0.000 | 0.000 | 1.000 |
| \\(X_6\\) | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | 1.000 | 1.000 | 0.000 | 8.000 |
| \\(X_7\\) | 0.000 | 0.000 | -3.500 | 3.500 | 0.000 | 1.500 | 0.000 | 1.000 | 9.000 |


## Iteration 2

Previous Tableau:

|   |\\(X_0\\) | \\(X_1\\) | \\(X_2\\) | \\(X_3\\) | \\(X_4\\) | \\(X_5\\) | \\(X_6\\) | \\(X_7\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | -1.000 | 0.000 | 0.000 | -2.000 |
| \\(X_4\\) | 0.000 | 0.000 | 3.500 | -3.500 | 1.000 | -0.500 | 0.000 | 0.000 | 2.000 |
| \\(X_1\\) | -1.000 | 1.000 | -0.500 | 0.500 | 0.000 | 0.500 | 0.000 | 0.000 | 1.000 |
| \\(X_6\\) | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | 1.000 | 1.000 | 0.000 | 8.000 |
| \\(X_7\\) | 0.000 | 0.000 | -3.500 | 3.500 | 0.000 | 1.500 | 0.000 | 1.000 | 9.000 |
### Pivot Operations

Variable to enter: \\(X_2\\)
Variable to leave: \\(X_4\\)
#### Row Operations:

1. \\(R_{X_4} = \frac{R_{X_4}}{3.5}\\)
1. \\(R_{C} = R_{C} - 2.0R_{X_4}\\)
2. \\(R_{X_1} = R_{X_1} + 0.5R_{X_4}\\)
3. \\(R_{X_6} = R_{X_6} - 2.0R_{X_4}\\)
4. \\(R_{X_7} = R_{X_7} + 3.5R_{X_4}\\)


Computed Tableau:

|   |\\(X_0\\) | \\(X_1\\) | \\(X_2\\) | \\(X_3\\) | \\(X_4\\) | \\(X_5\\) | \\(X_6\\) | \\(X_7\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 0.000 | 0.000 | -0.571 | -0.714 | 0.000 | 0.000 | -3.143 |
| \\(X_2\\) | 0.000 | 0.000 | 1.000 | -1.000 | 0.286 | -0.143 | 0.000 | 0.000 | 0.571 |
| \\(X_1\\) | -1.000 | 1.000 | 0.000 | 0.000 | 0.143 | 0.429 | 0.000 | 0.000 | 1.286 |
| \\(X_6\\) | 0.000 | 0.000 | 0.000 | 0.000 | -0.571 | 1.286 | 1.000 | 0.000 | 6.857 |
| \\(X_7\\) | 0.000 | 0.000 | 0.000 | 0.000 | 1.000 | 1.000 | 0.000 | 1.000 | 11.000 |


In [27]:
C @ X_star

0.0

In [29]:
simplex_two_phases(A, B, C, I)

(-3.1428571428571423,
 array([ 0.57142857,  1.28571429,  6.85714286, 11.        ]),
 array([2, 1, 6, 7]),
 array([[ 3,  1,  0,  0],
        [-1,  2,  0,  0],
        [ 3, -2,  1,  0],
        [-2, -3,  0,  1]]),
 array([[-1,  1,  3, -3,  1,  0,  0,  0],
        [-2,  2, -1,  1,  0,  1,  0,  0],
        [ 2, -2,  3, -3,  0,  0,  1,  0],
        [ 3, -3, -2,  2,  0,  0,  0,  1]]),
 2,
 2,
 {'second phase': {'title': 'Simplex method with feasible initial basis for granted',
   'debug_info_iteration_00': {'A_I': array([[1, 0, 0, 0],
           [0, 1, 0, 0],
           [0, 0, 1, 0],
           [0, 0, 0, 1]]),
    'A_I_inv': array([[1., 0., 0., 0.],
           [0., 1., 0., 0.],
           [0., 0., 1., 0.],
           [0., 0., 0., 1.]]),
    'J': [0, 5, 2, 3],
    'A_J': array([[-1,  1,  3, -3],
           [-2,  2, -1,  1],
           [ 2, -2,  3, -3],
           [ 3, -3, -2,  2]]),
    'x_I': array([3., 2., 6., 6.]),
    'x': array([0., 2., 0., 0., 3., 0., 6., 6.]),
    'π': array([0., 0., 0