In [2]:
%pip install numpy
%pip install sympy
%pip install scipy
%load_ext autoreload
%autoreload 2
from simplex_two_phases import simplex as simplex_two_phases
from simplex_tableau import simplex as simplex_tableau
from simplex_tableau import markdown_repr_T
from simplex import simplex

    
import numpy as np
from pprint import pprint
from IPython.display import Markdown, display
from itertools import combinations
from sympy import symbols, Matrix, solve
from scipy.optimize import linprog


solution_types = {
    -1: 'Unfeasible',
    1: 'Optimal finite solution found',
    2: 'Multiple optimal solutions found',
    3: 'Unbounded'
}

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Lista 5
## Exercício 3.22

In [2]:
# Instantiate the data for the default minimization
# problem in the form:
# z = min C.T @ X
# subject to:
#     A @ X = B

C = np.array([
    -3,
    -4,
    -2.5,
    0,
    0,
    0
])

A = np.array([
    [3, 4, 2, 1, 0, 0],
    [2, 1, 2, 0, 1, 0],
    [1, 3, 3, 0, 0, 1]
])

B = np.array([
    500,
    400,
    300
])

m, n = A.shape
I = [3, 4, 5]

Z_star, x_I, I_star, A_I, A, iterations, solution_type, debug_info = simplex_two_phases(A, B, C, I, debug = True)
#Z_star, x_star, I_star, iterations, solution_type = simplex(A, b, c, I, debug = True)
x_star = np.zeros(n)
x_star[I_star] = x_I
result_repr = f'''
Exercicio 3.22):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations + 1}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)
display('Simplex Steps:\n\n')
display(debug_info)


Exercicio 3.22):

Z_star = -528.5714285714286
x_star = [128.57142857   0.          57.14285714   0.          28.57142857
   0.        ]
I_star = [0 4 2]
iterations = 4
solution_type = 1 - Optimal finite solution found



'Simplex Steps:\n\n'

{'second phase': {'title': 'Simplex method with feasible initial basis for granted',
  'debug_info_iteration_00': {'A_I': array([[1, 0, 0],
          [0, 1, 0],
          [0, 0, 1]]),
   'A_I_inv': array([[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]]),
   'J': [0, 5, 2],
   'A_J': array([[3, 4, 2],
          [2, 1, 2],
          [1, 3, 3]]),
   'x_I': array([500., 400., 300.]),
   'x': array([  0., 300.,   0., 500., 400.,   0.]),
   'π': array([0., 0., 0.]),
   'z_0': 0.0,
   'c_hat_J': array([3. , 4. , 2.5]),
   'k': 1,
   'r': 2,
   'debug_info_from_r_who_leaves': {'description': 'Finding the variable that leaves the basis',
    'y_k': array([4., 1., 3.]),
    'ratios': array([125., 400., 100.]),
    'r': 2,
    'I_r': 5},
   'y_k': array([4., 1., 3.]),
   'previous I': array([3, 4, 5]),
   'previous J': [0, 1, 2],
   'computed I': array([3, 4, 1]),
   'computed J': [0, 5, 2]},
  'debug_info_iteration_01': {'A_I': array([[1, 0, 4],
          [0, 1, 1],
          [0, 0

## Exercício 3.23

In [3]:
# Instantiate the data for the default minimization
# problem in the form:
# z = min C.T @ X
# subject to:
#     A @ X = B

np.set_printoptions(suppress=True)

C = np.array([
    -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
])

A = np.array([
       [ 1.0e+00,  0.0e+00, -1.0e+00,  0.0e+00,  1.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 1.0e+00,  0.0e+00,  0.0e+00, -1.0e+00,  0.0e+00,  1.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  3.0e+01,  4.5e+03,  0.0e+00,  0.0e+00,  0.0e+00,
         1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  4.0e+01,  5.0e+03,  5.0e+03,  0.0e+00,  0.0e+00,
         0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  5.0e-01,  1.5e+02,  1.5e+02,  0.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00, -1.0e+00,  0.0e+00],
       [ 0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  1.0e+00]
])

B = np.array([
    0,
    0,
    150e3,
    100e3,
    600,
    600,
    800
])

m, n = A.shape
I = list(range(4,11))

Z_star, x_I, I_star, A_I, A, iterations, solution_type, debug_info = simplex_two_phases(A, B, C, I, debug = True)
#Z_star, x_star, I_star, iterations, solution_type = simplex(A, b, c, I, debug = True)
x_star = np.zeros(n)
x_star[I_star] = x_I
x_star = {
    f'x_{i:}': f'{x:.2f}' for i, x in enumerate(x_star)
}
result_repr = f'''
Exercicio 3.23):

Z_star = {Z_star}
x_star = {str(x_star)}
I_star = {I_star}
iterations = {iterations + 1}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)
display('Simplex Steps:\n\n')
display(debug_info)


Exercicio 3.23):

Z_star = -0.9999999999999993
x_star = {'x_0': '1.00', 'x_1': '600.00', 'x_2': '1.00', 'x_3': '1.00', 'x_4': '0.00', 'x_5': '0.00', 'x_6': '127500.00', 'x_7': '66000.00', 'x_8': '0.00', 'x_9': '0.00', 'x_10': '200.00'}
I_star = [ 0  2  6  7  3  1 10]
iterations = 5
solution_type = 1 - Optimal finite solution found



'Simplex Steps:\n\n'

{'first phase': {'first_phase_debug_info': {'title': 'Simplex method with feasible initial basis for granted',
   'debug_info_iteration_00': {'A_I': array([[1., 0., 0., 0., 0., 0., 0.],
           [0., 1., 0., 0., 0., 0., 0.],
           [0., 0., 1., 0., 0., 0., 0.],
           [0., 0., 0., 1., 0., 0., 0.],
           [0., 0., 0., 0., 1., 0., 0.],
           [0., 0., 0., 0., 0., 1., 0.],
           [0., 0., 0., 0., 0., 0., 1.]]),
    'A_I_inv': array([[1., 0., 0., 0., 0., 0., 0.],
           [0., 1., 0., 0., 0., 0., 0.],
           [0., 0., 1., 0., 0., 0., 0.],
           [0., 0., 0., 1., 0., 0., 0.],
           [0., 0., 0., 0., 1., 0., 0.],
           [0., 0., 0., 0., 0., 1., 0.],
           [0., 0., 0., 0., 0., 0., 1.]]),
    'J': [0, 11, 2, 3, 9],
    'A_J': array([[   1. ,    0. ,   -1. ,    0. ,    0. ],
           [   1. ,    0. ,    0. ,   -1. ,    0. ],
           [   0. ,   30. , 4500. ,    0. ,    0. ],
           [   0. ,   40. , 5000. , 5000. ,    0. ],
           [   0. , 

### Estudo dos valores do vetor X nas 2 Únicas Iterações da Fase 1 do Simplex para o Problema em Tela

In [4]:
X = list(debug_info['first phase']['first_phase_debug_info'][f'debug_info_iteration_{i:02d}']['x'] for i in range(2))
for x in X:
    display(x)

array([     0.,    600.,      0.,      0.,      0.,      0., 150000.,
       100000.,    600.,      0.,    800.,      0.])

array([     0.,    600.,      0.,      0.,      0.,      0., 132000.,
        76000.,    300.,      0.,    200.,      0.])

### Estudo dos valores do vetor X nas 4 Únicas Iterações da Fase 2 do Simplex para o Problema em Tela

In [5]:
X = list(debug_info['second phase'][f'debug_info_iteration_{i:02d}']['x'] for i in range(4))
for x in X:
    display(x)

array([     0.,    600.,      0.,      0.,      0.,      0., 132000.,
        76000.,    300.,      0.,    200.])

array([     0.,    600.,      0.,      0.,      0.,      0., 132000.,
        76000.,    300.,      0.,    200.])

array([     0.,    600.,      0.,    300.,      0.,      0., 132000.,
        76000.,      0.,      0.,    200.])

array([     1.,    600.,      1.,      1.,      0.,      0., 127500.,
        66000.,      0.,      0.,    200.])

### Estudo dos valores do vetor I nas 4 Únicas Iterações da Fase 2 do Simplex para o Problema em Tela

In [6]:
I = list(debug_info['second phase'][f'debug_info_iteration_{i:02d}']['computed I'] for i in range(4))
for i in I:
    display(i)

array([ 0,  5,  6,  7,  8,  1, 10])

array([ 0,  2,  6,  7,  8,  1, 10])

array([ 0,  2,  6,  7,  3,  1, 10])

array([ 0,  2,  6,  7,  3,  1, 10])

## Exercício 3.26

In [7]:
C = np.array([2, -2, -1, 1, 0, 0, 0, 0])
A = np.array([
    [-1,  1,  3, -3, 1, 0, 0, 0],
    [-2, 2, -1,  1, 0, 1, 0, 0],
    [2, -2,  3, -3, 0, 0, 1, 0],
    [3, -3, -2,  2, 0, 0, 0, 1]
])
B = np.array([3, 2, 6, 6])

m, n = A.shape
I = list(range(4,8))

solution = simplex_tableau(A, B, C, I)

'''
    Display solution
'''
Z_star = solution['Z_star']
I_star = solution['I_star']
X_star = np.zeros(n)
X_star[I_star] = solution['X_star']
solution_type = solution_types[
    solution['solution_type']
]
solution_md = f'''
## Solution

\\\\(X^{{*}}\\\\) = {repr(np.round(X_star, 2))}

\\\\(Z^{{*}} = {repr(np.round(Z_star, 5))} \\\\)

\\\\(\\text{{I}}^{{*}}\\\\) = {repr([
    '\\(X_' + str(i) + '\\)' for i in I_star
])}
'''
display(
    Markdown(
        solution_md
    )
)

'''
    Display Tableaus
'''
tableau_steps = solution['tableaus']
tableau_md = markdown_repr_T(tableau_steps)
display(
    Markdown(
        tableau_md
    )
)



## Solution

\\(X^{*}\\) = array([ 0.  ,  1.29,  0.57,  0.  ,  0.  ,  0.  ,  6.86, 11.  ])

\\(Z^{*} = -3.14286 \\)

\\(\text{I}^{*}\\) = ['\\(X_2\\)', '\\(X_1\\)', '\\(X_6\\)', '\\(X_7\\)']




## Iteration 1

Previous Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | \\(X_{7}\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | -2.000 | 2.000 | 1.000 | -1.000 | 0.000 | 0.000 | 0.000 | 0.000 | 0.000 |
| \\(X_{4}\\) | -1.000 | 1.000 | 3.000 | -3.000 | 1.000 | 0.000 | 0.000 | 0.000 | 3.000 |
| \\(X_{5}\\) | -2.000 | 2.000 | -1.000 | 1.000 | 0.000 | 1.000 | 0.000 | 0.000 | 2.000 |
| \\(X_{6}\\) | 2.000 | -2.000 | 3.000 | -3.000 | 0.000 | 0.000 | 1.000 | 0.000 | 6.000 |
| \\(X_{7}\\) | 3.000 | -3.000 | -2.000 | 2.000 | 0.000 | 0.000 | 0.000 | 1.000 | 6.000 |
### Pivot Operations

Variable to enter: \\(X_{1}\\)
Variable to leave: \\(X_{5}\\)
#### Row Operations:

1. \\(R_{X_{5}} \leftarrow \frac{R_{X_{5}}}{2.0}\\)
1. \\(R_{C} \leftarrow R_{C} - 2.0R_{X_{5}}\\)
2. \\(R_{X_{4}} \leftarrow R_{X_{4}} - 1.0R_{X_{5}}\\)
3. \\(R_{X_{6}} \leftarrow R_{X_{6}} + 2.0R_{X_{5}}\\)
4. \\(R_{X_{7}} \leftarrow R_{X_{7}} + 3.0R_{X_{5}}\\)


Computed Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | \\(X_{7}\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | -1.000 | 0.000 | 0.000 | -2.000 |
| \\(X_{4}\\) | 0.000 | 0.000 | 3.500 | -3.500 | 1.000 | -0.500 | 0.000 | 0.000 | 2.000 |
| \\(X_{1}\\) | -1.000 | 1.000 | -0.500 | 0.500 | 0.000 | 0.500 | 0.000 | 0.000 | 1.000 |
| \\(X_{6}\\) | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | 1.000 | 1.000 | 0.000 | 8.000 |
| \\(X_{7}\\) | 0.000 | 0.000 | -3.500 | 3.500 | 0.000 | 1.500 | 0.000 | 1.000 | 9.000 |


## Iteration 2

Previous Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | \\(X_{7}\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | -1.000 | 0.000 | 0.000 | -2.000 |
| \\(X_{4}\\) | 0.000 | 0.000 | 3.500 | -3.500 | 1.000 | -0.500 | 0.000 | 0.000 | 2.000 |
| \\(X_{1}\\) | -1.000 | 1.000 | -0.500 | 0.500 | 0.000 | 0.500 | 0.000 | 0.000 | 1.000 |
| \\(X_{6}\\) | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | 1.000 | 1.000 | 0.000 | 8.000 |
| \\(X_{7}\\) | 0.000 | 0.000 | -3.500 | 3.500 | 0.000 | 1.500 | 0.000 | 1.000 | 9.000 |
### Pivot Operations

Variable to enter: \\(X_{2}\\)
Variable to leave: \\(X_{4}\\)
#### Row Operations:

1. \\(R_{X_{4}} \leftarrow \frac{R_{X_{4}}}{3.5}\\)
1. \\(R_{C} \leftarrow R_{C} - 2.0R_{X_{4}}\\)
2. \\(R_{X_{1}} \leftarrow R_{X_{1}} + 0.5R_{X_{4}}\\)
3. \\(R_{X_{6}} \leftarrow R_{X_{6}} - 2.0R_{X_{4}}\\)
4. \\(R_{X_{7}} \leftarrow R_{X_{7}} + 3.5R_{X_{4}}\\)


Computed Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | \\(X_{7}\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 0.000 | 0.000 | -0.571 | -0.714 | 0.000 | 0.000 | -3.143 |
| \\(X_{2}\\) | 0.000 | 0.000 | 1.000 | -1.000 | 0.286 | -0.143 | 0.000 | 0.000 | 0.571 |
| \\(X_{1}\\) | -1.000 | 1.000 | 0.000 | 0.000 | 0.143 | 0.429 | 0.000 | 0.000 | 1.286 |
| \\(X_{6}\\) | 0.000 | 0.000 | 0.000 | 0.000 | -0.571 | 1.286 | 1.000 | 0.000 | 6.857 |
| \\(X_{7}\\) | 0.000 | 0.000 | 0.000 | 0.000 | 1.000 | 1.000 | 0.000 | 1.000 | 11.000 |


## Exercício 3.27

In [8]:
C = np.array([-2, -1, -6, 4, 0, 0, 0])
A = np.array([
    [1, 2,  4, -1, 1, 0, 0],
    [2, 3, -1,  1, 0, 1, 0],
    [1, 0,  1,  1, 0, 0, 1]
])
B = np.array([6, 12, 2])

m, n = A.shape
I = [0, 1, 3]

solution = simplex_tableau(A, B, C, I)

'''
    Display solution
'''
Z_star = solution['Z_star']
I_star = solution['I_star']
X_star = np.zeros(n)
X_star[I_star] = solution['X_star']
solution_type = solution_types[
    solution['solution_type']
]
solution_md = f'''
## Solution

\\\\(X^{{*}}\\\\) = {repr(np.round(X_star, 2))}

\\\\(Z^{{*}} = {repr(np.round(Z_star, 5))} \\\\)

\\\\(\\text{{I}}^{{*}}\\\\) = {repr([
    '\\(X_' + str(i) + '\\)' for i in I_star
])}
'''
display(
    Markdown(
        solution_md
    )
)

'''
    Display Tableaus
'''
tableaus = True
if tableaus:
    tableau_steps = solution['tableaus']
    tableau_md = markdown_repr_T(tableau_steps)
    display(
        Markdown(
            tableau_md
        )
    )


## Solution

\\(X^{*}\\) = array([ 0.67,  0.  ,  1.33,  0.  ,  0.  , 12.  ,  0.  ])

\\(Z^{*} = -9.33333 \\)

\\(\text{I}^{*}\\) = ['\\(X_0\\)', '\\(X_2\\)', '\\(X_5\\)']




## Iteration 1

Previous Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | -16.250 | 0.000 | -4.250 | 2.500 | -2.750 | -1.000 |
| \\(X_{0}\\) | 1.000 | 0.000 | 4.750 | 0.000 | 0.750 | -0.500 | 1.250 | 1.000 |
| \\(X_{1}\\) | 0.000 | 1.000 | -2.250 | 0.000 | -0.250 | 0.500 | -0.750 | 3.000 |
| \\(X_{3}\\) | 0.000 | 0.000 | -3.750 | 1.000 | -0.750 | 0.500 | -0.250 | 1.000 |
### Pivot Operations

Variable to enter: \\(X_{5}\\)
Variable to leave: \\(X_{3}\\)
#### Row Operations:

1. \\(R_{X_{3}} \leftarrow \frac{R_{X_{3}}}{0.5}\\)
1. \\(R_{C} \leftarrow R_{C} - 2.5R_{X_{3}}\\)
2. \\(R_{X_{0}} \leftarrow R_{X_{0}} + 0.5R_{X_{3}}\\)
3. \\(R_{X_{1}} \leftarrow R_{X_{1}} - 0.5R_{X_{3}}\\)


Computed Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 2.500 | -5.000 | -0.500 | 0.000 | -1.500 | -6.000 |
| \\(X_{0}\\) | 1.000 | 0.000 | 1.000 | 1.000 | 0.000 | 0.000 | 1.000 | 2.000 |
| \\(X_{1}\\) | 0.000 | 1.000 | 1.500 | -1.000 | 0.500 | 0.000 | -0.500 | 2.000 |
| \\(X_{5}\\) | 0.000 | 0.000 | -7.500 | 2.000 | -1.500 | 1.000 | -0.500 | 2.000 |


## Iteration 2

Previous Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 2.500 | -5.000 | -0.500 | 0.000 | -1.500 | -6.000 |
| \\(X_{0}\\) | 1.000 | 0.000 | 1.000 | 1.000 | 0.000 | 0.000 | 1.000 | 2.000 |
| \\(X_{1}\\) | 0.000 | 1.000 | 1.500 | -1.000 | 0.500 | 0.000 | -0.500 | 2.000 |
| \\(X_{5}\\) | 0.000 | 0.000 | -7.500 | 2.000 | -1.500 | 1.000 | -0.500 | 2.000 |
### Pivot Operations

Variable to enter: \\(X_{2}\\)
Variable to leave: \\(X_{1}\\)
#### Row Operations:

1. \\(R_{X_{1}} \leftarrow \frac{R_{X_{1}}}{1.5}\\)
1. \\(R_{C} \leftarrow R_{C} - 2.5R_{X_{1}}\\)
2. \\(R_{X_{0}} \leftarrow R_{X_{0}} - 1.0R_{X_{1}}\\)
3. \\(R_{X_{5}} \leftarrow R_{X_{5}} + 7.5R_{X_{1}}\\)


Computed Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | -1.667 | 0.000 | -3.333 | -1.333 | 0.000 | -0.667 | -9.333 |
| \\(X_{0}\\) | 1.000 | -0.667 | 0.000 | 1.667 | -0.333 | 0.000 | 1.333 | 0.667 |
| \\(X_{2}\\) | 0.000 | 0.667 | 1.000 | -0.667 | 0.333 | 0.000 | -0.333 | 1.333 |
| \\(X_{5}\\) | 0.000 | 5.000 | 0.000 | -3.000 | 1.000 | 1.000 | -3.000 | 12.000 |


In [9]:
from simplex_tableau import _markdown_T, _apply_pivot, _markdown_pivot_operations
T = np.copy(tableau_steps[0]['previous_T'])
I = [4, 5, 6]
display(
    Markdown(
        _markdown_T(T, I)
    )
)
r = 4
k = 0
T, pivot_operations = _apply_pivot(T, r, k, I)
display(
    Markdown(
        _markdown_pivot_operations(f'X_{k}', f'X_{r}', I, pivot_operations)
    )
)
I = [0, 5, 6]
display(
    Markdown(
        _markdown_T(T, I)
    )
)
r = 5
k = 1
T, pivot_operations = _apply_pivot(T, r, k, I)
display(
    Markdown(
        _markdown_pivot_operations(f'X_{k}', f'X_{r}', I, pivot_operations)
    )
)
I = [0, 1, 6]
display(
    Markdown(
        _markdown_T(T, I)
    )
)
# tirar x6, colocar x3
r = 6
k = 3
T, pivot_operations = _apply_pivot(T, r, k, I)
display(
    Markdown(
        _markdown_pivot_operations(f'X_{k}', f'X_{r}', I, pivot_operations)
    )
)
I = [0, 1, 3]
display(
    Markdown(
        _markdown_T(T, I)
    )
)

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | -16.250 | 0.000 | -4.250 | 2.500 | -2.750 | -1.000 |
| \\(X_{4}\\) | 1.000 | 0.000 | 4.750 | 0.000 | 0.750 | -0.500 | 1.250 | 1.000 |
| \\(X_{5}\\) | 0.000 | 1.000 | -2.250 | 0.000 | -0.250 | 0.500 | -0.750 | 3.000 |
| \\(X_{6}\\) | 0.000 | 0.000 | -3.750 | 1.000 | -0.750 | 0.500 | -0.250 | 1.000 |


### Pivot Operations

Variable to enter: \\(X_0\\)
Variable to leave: \\(X_4\\)
#### Row Operations:

1. \\(R_{X_{4}} \leftarrow \frac{R_{X_{4}}}{1.0}\\)
1. \\(R_{C} \leftarrow R_{C} - 0.0R_{X_{4}}\\)
2. \\(R_{X_{5}} \leftarrow R_{X_{5}} - 0.0R_{X_{4}}\\)
3. \\(R_{X_{6}} \leftarrow R_{X_{6}} - 0.0R_{X_{4}}\\)


|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | -16.250 | 0.000 | -4.250 | 2.500 | -2.750 | -1.000 |
| \\(X_{0}\\) | 1.000 | 0.000 | 4.750 | 0.000 | 0.750 | -0.500 | 1.250 | 1.000 |
| \\(X_{5}\\) | 0.000 | 1.000 | -2.250 | 0.000 | -0.250 | 0.500 | -0.750 | 3.000 |
| \\(X_{6}\\) | 0.000 | 0.000 | -3.750 | 1.000 | -0.750 | 0.500 | -0.250 | 1.000 |


### Pivot Operations

Variable to enter: \\(X_1\\)
Variable to leave: \\(X_5\\)
#### Row Operations:

1. \\(R_{X_{5}} \leftarrow \frac{R_{X_{5}}}{1.0}\\)
1. \\(R_{C} \leftarrow R_{C} - 0.0R_{X_{5}}\\)
2. \\(R_{X_{0}} \leftarrow R_{X_{0}} - 0.0R_{X_{5}}\\)
3. \\(R_{X_{6}} \leftarrow R_{X_{6}} - 0.0R_{X_{5}}\\)


|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | -16.250 | 0.000 | -4.250 | 2.500 | -2.750 | -1.000 |
| \\(X_{0}\\) | 1.000 | 0.000 | 4.750 | 0.000 | 0.750 | -0.500 | 1.250 | 1.000 |
| \\(X_{1}\\) | 0.000 | 1.000 | -2.250 | 0.000 | -0.250 | 0.500 | -0.750 | 3.000 |
| \\(X_{6}\\) | 0.000 | 0.000 | -3.750 | 1.000 | -0.750 | 0.500 | -0.250 | 1.000 |


### Pivot Operations

Variable to enter: \\(X_3\\)
Variable to leave: \\(X_6\\)
#### Row Operations:

1. \\(R_{X_{6}} \leftarrow \frac{R_{X_{6}}}{1.0}\\)
1. \\(R_{C} \leftarrow R_{C} - 0.0R_{X_{6}}\\)
2. \\(R_{X_{0}} \leftarrow R_{X_{0}} - 0.0R_{X_{6}}\\)
3. \\(R_{X_{1}} \leftarrow R_{X_{1}} - 0.0R_{X_{6}}\\)


|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | -16.250 | 0.000 | -4.250 | 2.500 | -2.750 | -1.000 |
| \\(X_{0}\\) | 1.000 | 0.000 | 4.750 | 0.000 | 0.750 | -0.500 | 1.250 | 1.000 |
| \\(X_{1}\\) | 0.000 | 1.000 | -2.250 | 0.000 | -0.250 | 0.500 | -0.750 | 3.000 |
| \\(X_{3}\\) | 0.000 | 0.000 | -3.750 | 1.000 | -0.750 | 0.500 | -0.250 | 1.000 |


Agora, aplicando o algoritmo a partir desta base

In [10]:
I = [0, 1, 3]

'''
    Display solution
'''
Z_star = solution['Z_star']
I_star = solution['I_star']
X_star = np.zeros(n)
X_star[I_star] = solution['X_star']
solution_type = solution_types[
    solution['solution_type']
]
solution_md = f'''
## Solution

\\\\(X^{{*}}\\\\) = {repr(np.round(X_star, 2))}

\\\\(Z^{{*}} = {repr(np.round(Z_star, 5))} \\\\)

\\\\(\\text{{I}}^{{*}}\\\\) = {repr([
    '\\(X_' + str(i) + '\\)' for i in I_star
])}
'''
display(
    Markdown(
        solution_md
    )
)

'''
    Display Tableaus
'''
tableaus = True
if tableaus:
    tableau_steps = solution['tableaus']
    tableau_md = markdown_repr_T(tableau_steps)
    display(
        Markdown(
            tableau_md
        )
    )


## Solution

\\(X^{*}\\) = array([ 0.67,  0.  ,  1.33,  0.  ,  0.  , 12.  ,  0.  ])

\\(Z^{*} = -9.33333 \\)

\\(\text{I}^{*}\\) = ['\\(X_0\\)', '\\(X_2\\)', '\\(X_5\\)']




## Iteration 1

Previous Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | -16.250 | 0.000 | -4.250 | 2.500 | -2.750 | -1.000 |
| \\(X_{0}\\) | 1.000 | 0.000 | 4.750 | 0.000 | 0.750 | -0.500 | 1.250 | 1.000 |
| \\(X_{1}\\) | 0.000 | 1.000 | -2.250 | 0.000 | -0.250 | 0.500 | -0.750 | 3.000 |
| \\(X_{3}\\) | 0.000 | 0.000 | -3.750 | 1.000 | -0.750 | 0.500 | -0.250 | 1.000 |
### Pivot Operations

Variable to enter: \\(X_{5}\\)
Variable to leave: \\(X_{3}\\)
#### Row Operations:

1. \\(R_{X_{3}} \leftarrow \frac{R_{X_{3}}}{0.5}\\)
1. \\(R_{C} \leftarrow R_{C} - 2.5R_{X_{3}}\\)
2. \\(R_{X_{0}} \leftarrow R_{X_{0}} + 0.5R_{X_{3}}\\)
3. \\(R_{X_{1}} \leftarrow R_{X_{1}} - 0.5R_{X_{3}}\\)


Computed Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 2.500 | -5.000 | -0.500 | 0.000 | -1.500 | -6.000 |
| \\(X_{0}\\) | 1.000 | 0.000 | 1.000 | 1.000 | 0.000 | 0.000 | 1.000 | 2.000 |
| \\(X_{1}\\) | 0.000 | 1.000 | 1.500 | -1.000 | 0.500 | 0.000 | -0.500 | 2.000 |
| \\(X_{5}\\) | 0.000 | 0.000 | -7.500 | 2.000 | -1.500 | 1.000 | -0.500 | 2.000 |


## Iteration 2

Previous Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 2.500 | -5.000 | -0.500 | 0.000 | -1.500 | -6.000 |
| \\(X_{0}\\) | 1.000 | 0.000 | 1.000 | 1.000 | 0.000 | 0.000 | 1.000 | 2.000 |
| \\(X_{1}\\) | 0.000 | 1.000 | 1.500 | -1.000 | 0.500 | 0.000 | -0.500 | 2.000 |
| \\(X_{5}\\) | 0.000 | 0.000 | -7.500 | 2.000 | -1.500 | 1.000 | -0.500 | 2.000 |
### Pivot Operations

Variable to enter: \\(X_{2}\\)
Variable to leave: \\(X_{1}\\)
#### Row Operations:

1. \\(R_{X_{1}} \leftarrow \frac{R_{X_{1}}}{1.5}\\)
1. \\(R_{C} \leftarrow R_{C} - 2.5R_{X_{1}}\\)
2. \\(R_{X_{0}} \leftarrow R_{X_{0}} - 1.0R_{X_{1}}\\)
3. \\(R_{X_{5}} \leftarrow R_{X_{5}} + 7.5R_{X_{1}}\\)


Computed Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | -1.667 | 0.000 | -3.333 | -1.333 | 0.000 | -0.667 | -9.333 |
| \\(X_{0}\\) | 1.000 | -0.667 | 0.000 | 1.667 | -0.333 | 0.000 | 1.333 | 0.667 |
| \\(X_{2}\\) | 0.000 | 0.667 | 1.000 | -0.667 | 0.333 | 0.000 | -0.333 | 1.333 |
| \\(X_{5}\\) | 0.000 | 5.000 | 0.000 | -3.000 | 1.000 | 1.000 | -3.000 | 12.000 |


## Exercício 3.28

In [11]:
C = np.array([3, -2, 1, -1, 0, 0, 0])
A = np.array([
    [ 2, -3, -1,  1, 1, 0, 0],
    [-1,  2,  2, -3, 0, 1, 0],
    [-1,  1, -4,  1, 0, 0, 1]
])
B = np.array([0, 1, 8])

m, n = A.shape
I = [4, 5, 6]

solution = simplex_tableau(A, B, C, I)

'''
    Display solution
'''
Z_star = solution['Z_star']
I_star = solution['I_star']
X_star = np.zeros(n)
X_star[I_star] = solution['X_star']
solution_type = solution_types[
    solution['solution_type']
]
solution_md = f'''
## Solution

Solution type: {solution_type}

\\\\(X^{{*}}\\\\) = {repr(np.round(X_star, 2))}

\\\\(Z^{{*}} = {repr(np.round(Z_star, 5))} \\\\)

\\\\(\\text{{I}}^{{*}}\\\\) = {repr([
    '\\(X_' + str(i) + '\\)' for i in I_star
])}
'''
display(
    Markdown(
        solution_md
    )
)

'''
    Display Tableaus
'''
tableaus = True
if tableaus:
    tableau_steps = solution['tableaus']
    tableau_md = markdown_repr_T(tableau_steps)
    display(
        Markdown(
            tableau_md
        )
    )


## Solution

Solution type: Unbounded

\\(X^{*}\\) = array([ 0.,  5.,  0.,  3., 12.,  0.,  0.])

\\(Z^{*} = -13.0 \\)

\\(\text{I}^{*}\\) = ['\\(X_4\\)', '\\(X_1\\)', '\\(X_3\\)']




## Iteration 1

Previous Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | -3.000 | 2.000 | -1.000 | 1.000 | 0.000 | 0.000 | 0.000 | 0.000 |
| \\(X_{4}\\) | 2.000 | -3.000 | -1.000 | 1.000 | 1.000 | 0.000 | 0.000 | 0.000 |
| \\(X_{5}\\) | -1.000 | 2.000 | 2.000 | -3.000 | 0.000 | 1.000 | 0.000 | 1.000 |
| \\(X_{6}\\) | -1.000 | 1.000 | -4.000 | 1.000 | 0.000 | 0.000 | 1.000 | 8.000 |
### Pivot Operations

Variable to enter: \\(X_{1}\\)
Variable to leave: \\(X_{5}\\)
#### Row Operations:

1. \\(R_{X_{5}} \leftarrow \frac{R_{X_{5}}}{2.0}\\)
1. \\(R_{C} \leftarrow R_{C} - 2.0R_{X_{5}}\\)
2. \\(R_{X_{4}} \leftarrow R_{X_{4}} + 3.0R_{X_{5}}\\)
3. \\(R_{X_{6}} \leftarrow R_{X_{6}} - 1.0R_{X_{5}}\\)


Computed Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | -2.000 | 0.000 | -3.000 | 4.000 | 0.000 | -1.000 | 0.000 | -1.000 |
| \\(X_{4}\\) | 0.500 | 0.000 | 2.000 | -3.500 | 1.000 | 1.500 | 0.000 | 1.500 |
| \\(X_{1}\\) | -0.500 | 1.000 | 1.000 | -1.500 | 0.000 | 0.500 | 0.000 | 0.500 |
| \\(X_{6}\\) | -0.500 | 0.000 | -5.000 | 2.500 | 0.000 | -0.500 | 1.000 | 7.500 |


## Iteration 2

Previous Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | -2.000 | 0.000 | -3.000 | 4.000 | 0.000 | -1.000 | 0.000 | -1.000 |
| \\(X_{4}\\) | 0.500 | 0.000 | 2.000 | -3.500 | 1.000 | 1.500 | 0.000 | 1.500 |
| \\(X_{1}\\) | -0.500 | 1.000 | 1.000 | -1.500 | 0.000 | 0.500 | 0.000 | 0.500 |
| \\(X_{6}\\) | -0.500 | 0.000 | -5.000 | 2.500 | 0.000 | -0.500 | 1.000 | 7.500 |
### Pivot Operations

Variable to enter: \\(X_{3}\\)
Variable to leave: \\(X_{6}\\)
#### Row Operations:

1. \\(R_{X_{6}} \leftarrow \frac{R_{X_{6}}}{2.5}\\)
1. \\(R_{C} \leftarrow R_{C} - 4.0R_{X_{6}}\\)
2. \\(R_{X_{4}} \leftarrow R_{X_{4}} + 3.5R_{X_{6}}\\)
3. \\(R_{X_{1}} \leftarrow R_{X_{1}} + 1.5R_{X_{6}}\\)


Computed Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | -1.200 | 0.000 | 5.000 | 0.000 | 0.000 | -0.200 | -1.600 | -13.000 |
| \\(X_{4}\\) | -0.200 | 0.000 | -5.000 | 0.000 | 1.000 | 0.800 | 1.400 | 12.000 |
| \\(X_{1}\\) | -0.800 | 1.000 | -2.000 | 0.000 | 0.000 | 0.200 | 0.600 | 5.000 |
| \\(X_{3}\\) | -0.200 | 0.000 | -2.000 | 1.000 | 0.000 | -0.200 | 0.400 | 3.000 |


Como \\(X_2\\) é ilimitada, ou seja, nenhuma variável da base limita seu crescimento, é interessante sempre adicionar valores à variável \\(X_2\\) para que a medida em que \\(X_2 \rightarrow \infty, \quad Z^{*} \rightarrow - \infty \\). Isso pode ser obtido através da base \\(I^{*} = [X_4, X_1, X_3]\\) como:

\\[
    X_I = {A_I}^{-1} \overline{b} - \left[ y_k \right] x_k
\\]

Como \\(k = 2\\) e \\(b^{T} = \left[ 12, 5, 3 \right] \\), logo:

\\[
    X^{*} = \left\{
        \begin{bmatrix}
            \underline{{A_I}^{-1} \overline{b}} \\
            0 \\
            \vdots \\
            0 \\
            \vdots \\
            0
        \end{bmatrix} + x_k \ 
        \begin{bmatrix}
            \underline{- y_k} \\
            0 \\
            \vdots \\
            1 \\
            \vdots \\
            0
        \end{bmatrix} : x_k \geq 0
    \right\}
\\]

Onde o vetor \\( 
    \begin{bmatrix}
        \underline{- y_k} \\
        0 \\
        \vdots \\
        1 \\
        \vdots \\
        0
    \end{bmatrix}
\\) representa a direção \\(d\\) do crescimento da variável ilimitada e é composto nos índices básicos pelos valores \\(- y_k\\) onde \\(y_k\\) corresponde à coluna \\(k\\) da matriz de \\(A\\) de restições — dada por \\(A_{\left[ :, k \right]}\\) — e nos índices básicos por zeros, exceto na k-ésima posição das variáveis não-básicas.

Assim, temos que

\\[
    X^{*} = \left\{
        \begin{bmatrix}
            12 \\
             5 \\
             3 \\
             0 \\
             0 \\
             0 \\
             0
        \end{bmatrix} + x_2 \ 
        \begin{bmatrix}
             5 \\
             2 \\
             2 \\
             0 \\
             0 \\
             1 \\
             0
        \end{bmatrix} = 
        \begin{bmatrix}
            12 + 5 x_2 \\
             5 + 2 x_2 \\
             3 + 2 x_2 \\
             0 \\
             0 \\
             x_2 \\
             0
        \end{bmatrix}
    \right\}
\\]

Considerando \\(I = [4, 1, 3]\\) e \\(J = [0, 5, 2, 6]\\)

\\[
    X^{*} =
    \begin{bmatrix}
            0 \\
            5 + 2 x_2 \\
            x_2  \\
            3 + 2 x_2 \\
            12 + 5 x_2 \\
            0 \\
            0
    \end{bmatrix}
\\]

Agora, o exercício solicita-nos um valor de x2 que garanta que a função objetivo seja maior ou igual a 3500. Com o auxilio da biblioteca sympy (computação simbolica) é possível encontrar de imediato qual valor satisfaz a condição dado que desejamos:

\\[
    C^{T} \cdot \begin{bmatrix}
            0 \\
            5 + 2 x_2 \\
            x_2  \\
            3 + 2 x_2 \\
            12 + 5 x_2 \\
            0 \\
            0
    \end{bmatrix} \geq 3500
\\]

In [12]:
from sympy import symbols, Matrix, solve

alpha = symbols('α')

X_unbounded = Matrix([
    0,
    5 + 2 * alpha,
    alpha,
    3 + 2* alpha,
    12 + 5 * alpha,
    0,
    0
])
display(C.dot(X_unbounded))
display(
    Markdown(
        repr(solve(C.dot(X_unbounded) + 3500))
    )
)

array([-5*α - 13], dtype=object)

{α: 3487/5}

In [13]:
alpha = 3487/5

X_unbounded = np.array([
    0,
    5 + 2 * alpha,
    alpha,
    3 + 2* alpha,
    12 + 5 * alpha,
    0,
    0
])

C @ X_unbounded

-3500.0

Portanto, \\(X_2 \geq \frac{3487}{5}\\) faz com que \\(Z^{*} \geq -3500 \therefore Z^{*} \geq 3500\\), considerando a conversão do problema de minimização adaptado para o problema original de maximização.

In [ ]:
X_unbounded

## Exercício 3.29

In [ ]:
A = np.array([
    [  5,   1,   -1,   2, 1, 0, 1,  0, 0,  0, 0, 0],
    [  5,   1,   -1,   2, 1, 0, 0, -1, 0,  0, 0, 0],
    [-14,  -3,    3,  -5, 0, 1, 0,  0, 1,  0, 0, 0],
    [-14,  -3,    3,  -5, 0, 1, 0,  0, 0, -1, 0, 0],
    [  2, 0.5, -0.5, 0.5, 0, 0, 0,  0, 0,  0, 1, 0],
    [  3, 0.5,  0.5, 1.5, 0, 0, 0,  0, 0,  0, 0, 1]
])
B = np.array([
     12,
     12,
      2,
      2,
    2.5,
      3
])
C = np.array([-11, -2, 1, -3, -4, -1, 0, 0, 0, 0, 0, 0])

m, n = A.shape
I = [6, 4, 8, 5, 10, 11]

solution = simplex_tableau(A, B, C, I)

'''
    Display solution
'''
Z_star = solution['Z_star']
I_star = solution['I_star']
X_star = np.zeros(n)
X_star[I_star] = solution['X_star']
solution_type = solution_types[
    solution['solution_type']
]
solution_md = f'''
## Solution

Solution type: {solution_type}

\\\\(X^{{*}}\\\\) = {repr(np.round(X_star, 2))}

\\\\(Z^{{*}} = {repr(np.round(Z_star, 5))} \\\\)

\\\\(\\text{{I}}^{{*}}\\\\) = {repr([
    '\\(X_' + str(i) + '\\)' for i in I_star
])}
'''
display(
    Markdown(
        solution_md
    )
)

'''
    Display Tableaus
'''
tableaus = True
if tableaus:
    tableau_steps = solution['tableaus']
    tableau_md = markdown_repr_T(tableau_steps)
    display(
        Markdown(
            tableau_md
        )
    )

In [ ]:
%pip install scipy
from scipy.optimize import linprog
result = linprog(C, A_eq = A, b_eq = B, method='highs')
print('Result comparison, we found the optimal solution through our tableaus')
display(result)

## Exercício 3.30

Letra a)

In [ ]:
A = np.array([
    [2, 1, 0, 1, 0, 0],
    [3, 3, 1, 0, 1, 0],
    [1, 2, 2, 0, 0, 1]
])

B = np.array([
    6000,
    9000,
    4000
])

C = np.array([
    10, 15, 5, 0, 0, 0
])

maximum = -float('inf')
for i, I in enumerate(combinations(range(6), 3)):
    if np.linalg.det(A[:,I]) == 0:
        continue
    x_I = np.linalg.solve(A[:,I], B)
    x = np.zeros(6)
    x[[I]] = x_I
    if np.all(x >= 0): # solucao valida
        z = C @ x
        if z > maximum: # devemos atualizar os valores
            X_star = x
            Z_star = z
            I_star = I
            maximum = z
            ith_combination = i + 1
display(f'I_star: {I_star}')
display(f'X_star: {X_star}')
display(f'Z_star: {Z_star}')

Letra b)

In [ ]:
I = list(I_star)
solution = simplex_tableau(A, B, -C, I)

'''
    Display solution
'''
m, n = A.shape
Z_star = solution['Z_star']
I_star = solution['I_star']
X_star = np.zeros(n)
X_star[I_star] = solution['X_star']
solution_type = solution_types[
    solution['solution_type']
]
solution_md = f'''
## Solution

Solution type: {solution_type}

\\\\(X^{{*}}\\\\) = {repr(np.round(X_star, 2))}

\\\\(Z^{{*}} = {repr(np.round(Z_star, 5))} \\\\)

\\\\(\\text{{I}}^{{*}}\\\\) = {repr([
    '\\(X_' + str(i) + '\\)' for i in I_star
])}
'''
display(
    Markdown(
        solution_md
    )
)

'''
    Display Tableaus
'''
tableaus = True
if tableaus:
    tableau_steps = solution['tableaus']
    tableau_md = markdown_repr_T(tableau_steps)
    display(
        Markdown(
            tableau_md
        )
    )

In [ ]:
A = np.hstack((A[:,:3], np.array([
    [2],
    [4],
    [2]
]), A[:,3:]))
C = np.hstack((C[:3],[50003/3000],C[3:]))

I = list([4, 5, 6])
solution = simplex_tableau(A, B, -C, I)

'''
    Display solution
'''
m, n = A.shape
Z_star = solution['Z_star']
I_star = solution['I_star']
X_star = np.zeros(n)
X_star[I_star] = solution['X_star']
solution_type = solution_types[
    solution['solution_type']
]
solution_md = f'''
## Solution

Solution type: {solution_type}

\\\\(X^{{*}}\\\\) = {repr(np.round(X_star, 2))}

\\\\(Z^{{*}} = {repr(np.round(Z_star, 5))} \\\\)

\\\\(\\text{{I}}^{{*}}\\\\) = {repr([
    '\\(X_' + str(i) + '\\)' for i in I_star
])}
'''
display(
    Markdown(
        solution_md
    )
)

'''
    Display Tableaus
'''
tableaus = True
if tableaus:
    tableau_steps = solution['tableaus']
    tableau_md = markdown_repr_T(tableau_steps)
    display(
        Markdown(
            tableau_md
        )
    )

In [ ]:
A, B, C

In [ ]:
%pip install scipy
from scipy.optimize import linprog
result = linprog(-C, A_eq = A, b_eq = B, method='highs')
print('Result comparison, we found the optimal solution through our tableaus')
display(result)

## Exercício 3.31

In [ ]:
A = np.array([
    [20, 15, -1, 1, 0, 0],
    [1,   0,  0, 0, 1, 0],
    [0,   1,  0, 0, 0, 1]
])
B = np.array([
    60000,
     2000,
     4000
])
C = np.array([-60, -30, 14, 0, 0, 0])

m, n = A.shape
I = [3, 0, 5]

solution = simplex_tableau(A, B, C, I)

'''
    Display solution
'''
Z_star = solution['Z_star']
I_star = solution['I_star']
X_star = np.zeros(n)
X_star[I_star] = solution['X_star']
solution_type = solution_types[
    solution['solution_type']
]
solution_md = f'''
## Solution

Solution type: {solution_type}

\\\\(X^{{*}}\\\\) = {repr(np.round(X_star, 2))}

\\\\(Z^{{*}} = {repr(np.round(Z_star, 5))} \\\\)

\\\\(\\text{{I}}^{{*}}\\\\) = {repr([
    '\\(X_' + str(i) + '\\)' for i in I_star
])}
'''
display(
    Markdown(
        solution_md
    )
)

'''
    Display Tableaus
'''
tableaus = True
if tableaus:
    tableau_steps = solution['tableaus']
    tableau_md = markdown_repr_T(tableau_steps)
    display(
        Markdown(
            tableau_md
        )
    )

## Exercício 5.1

In [ ]:
from simplex_two_phases import _simplex_find_feasible_initial_basis
from revised_simplex_tableau import revised_simplex_tableau, markdown_repr_T
from utils import array_to_markdown

results_md = ''

C = np.array([1, 4, -7, 1, 5, 0, 0, 0, 0])
A = np.array([
    [1, -0.75, 2, -0.25, 0, 1,  0, 0,  0],
    [1, -0.75, 2, -0.25, 0, 0, -1, 0,  0],
    [0, -0.25, 3, -0.75, 1, 0,  0, 1,  0],
    [0, -0.25, 3, -0.75, 1, 0,  0, 0, -1],
])
B = np.array([
    6,
    6,
    5,
    5
])
I = [5, 6, 7, 8]

I_sanitized, A_I_sanitized, A_sanitized, B_sanitized, feasible, iters_count, debug_info = _simplex_find_feasible_initial_basis(A, B, C, I)

solution = revised_simplex_tableau(A, B, C, I_sanitized)
results_md += markdown_repr_T(solution)

display(
    Markdown(results_md)
)

## Result Comparison through scipy

In [ ]:
from scipy.optimize import linprog
result = linprog(C, A_eq = A, b_eq = B, method='highs')
print('Result comparison, we found the optimal solution through our tableaus')
display(result)

## Exercício 5.2

In [ ]:
from revised_simplex_tableau import revised_simplex_tableau, markdown_repr_T
A = np.array([
    [-1,  2, -1, 1, 0, 0],
    [ 1,  1,  1, 0, 1, 0],
    [ 2, -1, -1, 0, 0, 1]
])
B = np.array([
    4,
    7,
    5
])
C = np.array([0, 2, -1, 0, 0, 0])
I = [3, 4, 5]
solution = revised_simplex_tableau(A, B, C, I)
results_md = markdown_repr_T(solution)

display(
    Markdown(results_md)
)
display(
    solution
)

## Result Comparison through scipy

In [ ]:
from scipy.optimize import linprog
result = linprog(C, A_eq = A, b_eq = B, method='highs')
print('Result comparison, we found the optimal solution through our tableaus')
display(result)

## Exercício 5.3

In [ ]:
from revised_simplex_tableau import revised_simplex_tableau, markdown_repr_T
A = np.array([
    [8, 3, 4, 1, 1, 0, 0],
    [2, 1, 1, 5, 0, 1, 0],
    [1, 4, 5, 2, 0, 0, 1]
])
B = np.array([
    7,
    3,
    8
])
C = np.array([-3, -2, -1, -1, 0, 0, 0])
I = [4, 5, 6]
solution = revised_simplex_tableau(A, B, C, I)
results_md = markdown_repr_T(solution)

display(
    Markdown(results_md)
)
display(
    solution
)

## Result Comparison through scipy

In [ ]:
from scipy.optimize import linprog
result = linprog(C, A_eq = A, b_eq = B, method='highs')
print('Result comparison, we found the optimal solution through our tableaus')
display(result)

## Exercício 5.7

In [ ]:
from revised_simplex_tableau import revised_simplex_tableau, markdown_repr_T
from simplex_two_phases import _simplex_find_feasible_initial_basis
from utils import array_to_markdown

slack_excess_matrix = np.eye(9)
excess_indices = [1, 3, 4, 5]
for excess_index in excess_indices:
    slack_excess_matrix[
        excess_index, excess_index
    ] = -1

A = np.array([
    [1, 1, 0, 1, 0],
    [1, 1, 0, 1, 0],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1],
    [1, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [1, 0, 0, 0, 0],
    [0,12,16, 0, 0],
    [0, 0, 0,12,16]
])

A = np.hstack((A, slack_excess_matrix))

B = np.array([
    400,
    400,
    500,
    500,
    250,
    200,
    200,
    4500,
    6000
])
C = np.array([
    450, 420, 560, 480, 640, 0, 0, 0, 0, 0, 0, 0, 0, 0
])
I = list(range(5,14))

I_sanitized, A_I_sanitized, A_sanitized, B_sanitized, feasible, iters_count, debug_info = _simplex_find_feasible_initial_basis(A, B, C, I)

solution = revised_simplex_tableau(A, B, C, list(I_sanitized))

results_md = markdown_repr_T(solution)

display(
    Markdown(results_md)
)

## Result Comparison through scipy

In [ ]:
from scipy.optimize import linprog
result = linprog(C, A_eq = A, b_eq = B, method='highs')
print('Result comparison, we found the optimal solution through our tableaus')
display(result)
display(result['x'])

### Showing that the problem admits multiple optimal solutions through different solutions that respects the same constraints and retrieves the same optimal value through different X values

In [ ]:
print('Same constraints?', np.all(A @ result['x'] == A @ solution[4]['X']))
print('Same optimal cost?', np.isclose(C @ result['x'], C @ solution[4]['X']))
print('Same values for variables?', np.all(result['x'] == solution[4]['X']))

### Building the solution in function of \\(x_9\\)

In [ ]:
from sympy import symbols, Matrix, latex
I = solution[4]['I']
J = solution[4]['J']
k = J [
    solution[4]['k']
]
_, n = A.shape
A_I_inv = solution[4]['T'][1:,:-1]
x_k = symbols(f'x_{k}')
x_I = A_I_inv @ B - A_I_inv @ A_k * x_k
x = np.zeros(n, dtype=object)
x[k] = x_k
x[I] = x_I.flatten()
x = Matrix(x)
display(
    x
)
display(
    Markdown(
        f'Does A @ x for any \\\\(x_{{{k}}}\\\\) respects the constraints? {'Yes' if A @ x == Matrix(B) else 'No'}'
    )
)

### Finding upper limits for \\(x_9\\) that will keep non negativity constraints

In [ ]:
upper_limit = solve(43.75 - 0.75*x_k).pop()

answer = f'''
$$
\\begin{{aligned}}
& {latex(x)}, \\\\
& 0 \\leq x_{{{k}}} \\leq {f'{upper_limit:.2f}'}
\\end{{aligned}}
$$
'''

display(
    Markdown(
        answer
    )
)

### Testing $x_9$ limits

In [1]:
domain = np.linspace(0, 58.5, int(1/0.001 - 1))
points_greater_than_upper_limit = len(domain[ domain > upper_limit])
non_negativity_constraints_violated = 0
for d in domain:
    if np.any(np.array(x.subs(x_k, d)) < 0):
        non_negativity_constraints_violated += 1
display(f'Points greater than {upper_limit:.2f} in our linspace: {points_greater_than_upper_limit}')
display(f'Non negativity constraints violated for x in that same linspace: {non_negativity_constraints_violated}')

<class 'NameError'>: name 'np' is not defined

## Exemplo com ciclos

In [12]:
#from revised_simplex_tableau import revised_simplex_tableau, markdown_repr_T
from simplex_tableau import simplex_tableau, markdown_repr_T
from utils import array_to_markdown

results_md = ''

C = np.array([0, 0, 0, -3/4, 20, -1/2, 6])
A = np.array([
    [1, 0, 0, 1/4,  -8,   -1, 9],
    [0, 1, 0, 1/2, -12, -1/2, 3],
    [0, 0, 1,   0,   0,    1, 0]
])
B = np.array([
    0,
    0,
    1
])
I = [0, 1, 2]

solution = simplex_tableau(A, B, C, I, cycles_allowed = False)
results_md += markdown_repr_T(solution['tableaus'])

display(
    Markdown(results_md)
)



## Iteration 1

Previous Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 0.000 | 0.750 | -20.000 | 0.500 | -6.000 | 0.000 |
| \\(X_{0}\\) | 1.000 | 0.000 | 0.000 | 0.250 | -8.000 | -1.000 | 9.000 | 0.000 |
| \\(X_{1}\\) | 0.000 | 1.000 | 0.000 | 0.500 | -12.000 | -0.500 | 3.000 | 0.000 |
| \\(X_{2}\\) | 0.000 | 0.000 | 1.000 | 0.000 | 0.000 | 1.000 | 0.000 | 1.000 |
### Pivot Operations

Variable to enter: \\(X_{3}\\)
Variable to leave: \\(X_{1}\\)
#### Row Operations:

1. \\(R_{X_{1}} \leftarrow \frac{R_{X_{1}}}{0.5}\\)
1. \\(R_{C} \leftarrow R_{C} - 0.75R_{X_{1}}\\)
2. \\(R_{X_{0}} \leftarrow R_{X_{0}} - 0.25R_{X_{1}}\\)
3. \\(R_{X_{2}} \leftarrow R_{X_{2}} - 0.0R_{X_{1}}\\)


Computed Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | -1.500 | 0.000 | 0.000 | -2.000 | 1.250 | -10.500 | 0.000 |
| \\(X_{0}\\) | 1.000 | -0.500 | 0.000 | 0.000 | -2.000 | -0.750 | 7.500 | 0.000 |
| \\(X_{3}\\) | 0.000 | 2.000 | 0.000 | 1.000 | -24.000 | -1.000 | 6.000 | 0.000 |
| \\(X_{2}\\) | 0.000 | 0.000 | 1.000 | 0.000 | 0.000 | 1.000 | 0.000 | 1.000 |


## Iteration 2

Previous Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | -1.500 | 0.000 | 0.000 | -2.000 | 1.250 | -10.500 | 0.000 |
| \\(X_{0}\\) | 1.000 | -0.500 | 0.000 | 0.000 | -2.000 | -0.750 | 7.500 | 0.000 |
| \\(X_{3}\\) | 0.000 | 2.000 | 0.000 | 1.000 | -24.000 | -1.000 | 6.000 | 0.000 |
| \\(X_{2}\\) | 0.000 | 0.000 | 1.000 | 0.000 | 0.000 | 1.000 | 0.000 | 1.000 |
### Pivot Operations

Variable to enter: \\(X_{5}\\)
Variable to leave: \\(X_{2}\\)
#### Row Operations:

1. \\(R_{X_{2}} \leftarrow \frac{R_{X_{2}}}{1.0}\\)
1. \\(R_{C} \leftarrow R_{C} - 1.25R_{X_{2}}\\)
2. \\(R_{X_{0}} \leftarrow R_{X_{0}} + 0.75R_{X_{2}}\\)
3. \\(R_{X_{3}} \leftarrow R_{X_{3}} + 1.0R_{X_{2}}\\)


Computed Tableau:

|   |\\(X_{0}\\) | \\(X_{1}\\) | \\(X_{2}\\) | \\(X_{3}\\) | \\(X_{4}\\) | \\(X_{5}\\) | \\(X_{6}\\) | RHS |
|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | -1.500 | -1.250 | 0.000 | -2.000 | 0.000 | -10.500 | -1.250 |
| \\(X_{0}\\) | 1.000 | -0.500 | 0.750 | 0.000 | -2.000 | 0.000 | 7.500 | 0.750 |
| \\(X_{3}\\) | 0.000 | 2.000 | 1.000 | 1.000 | -24.000 | 0.000 | 6.000 | 1.000 |
| \\(X_{5}\\) | 0.000 | 0.000 | 1.000 | 0.000 | 0.000 | 1.000 | 0.000 | 1.000 |
