In [1]:
%pip install numpy
%pip install sympy
%load_ext autoreload
%autoreload 2
from simplex_two_phases import simplex as simplex_two_phases
from simplex import simplex
    
import numpy as np
from pprint import pprint

solution_types = {
    -1: 'Unfeasible',
    1: 'Optimal finite solution found',
    2: 'Multiple optimal solutions found',
    3: 'Unbounded'
}

# Lista 5
## Exercício 3.22

In [ ]:
# Instantiate the data for the default minimization
# problem in the form:
# z = min C.T @ X
# subject to:
#     A @ X = B

C = np.array([
    -3,
    -4,
    -2.5,
    0,
    0,
    0
])

A = np.array([
    [3, 4, 2, 1, 0, 0],
    [2, 1, 2, 0, 1, 0],
    [1, 3, 3, 0, 0, 1]
])

B = np.array([
    500,
    400,
    300
])

m, n = A.shape
I = [3, 4, 5]

Z_star, x_I, I_star, A_I, A, iterations, solution_type, debug_info = simplex_two_phases(A, B, C, I, debug = True)
#Z_star, x_star, I_star, iterations, solution_type = simplex(A, b, c, I, debug = True)
x_star = np.zeros(n)
x_star[I_star] = x_I
result_repr = f'''
Exercicio 3.22):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations + 1}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)
display('Simplex Steps:\n\n')
display(debug_info)

## Exercício 3.23

In [24]:
# Instantiate the data for the default minimization
# problem in the form:
# z = min C.T @ X
# subject to:
#     A @ X = B

np.set_printoptions(suppress=True)

C = np.array([
    -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
])

A = np.array([
       [ 1.0e+00,  0.0e+00, -1.0e+00,  0.0e+00,  1.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 1.0e+00,  0.0e+00,  0.0e+00, -1.0e+00,  0.0e+00,  1.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  3.0e+01,  4.5e+03,  0.0e+00,  0.0e+00,  0.0e+00,
         1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  4.0e+01,  5.0e+03,  5.0e+03,  0.0e+00,  0.0e+00,
         0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  5.0e-01,  1.5e+02,  1.5e+02,  0.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00, -1.0e+00,  0.0e+00],
       [ 0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  1.0e+00]
])

B = np.array([
    0,
    0,
    150e3,
    100e3,
    600,
    600,
    800
])

m, n = A.shape
I = list(range(4,11))

Z_star, x_I, I_star, A_I, A, iterations, solution_type, debug_info = simplex_two_phases(A, B, C, I, debug = True)
#Z_star, x_star, I_star, iterations, solution_type = simplex(A, b, c, I, debug = True)
x_star = np.zeros(n)
x_star[I_star] = x_I
x_star = {
    f'x_{i:}': f'{x:.2f}' for i, x in enumerate(x_star)
}
result_repr = f'''
Exercicio 3.23):

Z_star = {Z_star}
x_star = {str(x_star)}
I_star = {I_star}
iterations = {iterations + 1}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)
display('Simplex Steps:\n\n')
display(debug_info)


Exercicio 3.23):

Z_star = -0.9999999999999993
x_star = {'x_0': '1.00', 'x_1': '600.00', 'x_2': '1.00', 'x_3': '1.00', 'x_4': '0.00', 'x_5': '0.00', 'x_6': '127500.00', 'x_7': '66000.00', 'x_8': '0.00', 'x_9': '0.00', 'x_10': '200.00'}
I_star = [ 0  2  6  7  3  1 10]
iterations = 5
solution_type = 1 - Optimal finite solution found



'Simplex Steps:\n\n'

{'first phase': {'first_phase_debug_info': {'title': 'Simplex method with feasible initial basis for granted',
   'debug_info_iteration_00': {'A_I': array([[1., 0., 0., 0., 0., 0., 0.],
           [0., 1., 0., 0., 0., 0., 0.],
           [0., 0., 1., 0., 0., 0., 0.],
           [0., 0., 0., 1., 0., 0., 0.],
           [0., 0., 0., 0., 1., 0., 0.],
           [0., 0., 0., 0., 0., 1., 0.],
           [0., 0., 0., 0., 0., 0., 1.]]),
    'A_I_inv': array([[1., 0., 0., 0., 0., 0., 0.],
           [0., 1., 0., 0., 0., 0., 0.],
           [0., 0., 1., 0., 0., 0., 0.],
           [0., 0., 0., 1., 0., 0., 0.],
           [0., 0., 0., 0., 1., 0., 0.],
           [0., 0., 0., 0., 0., 1., 0.],
           [0., 0., 0., 0., 0., 0., 1.]]),
    'J': [0, 11, 2, 3, 9],
    'A_J': array([[   1. ,    0. ,   -1. ,    0. ,    0. ],
           [   1. ,    0. ,    0. ,   -1. ,    0. ],
           [   0. ,   30. , 4500. ,    0. ,    0. ],
           [   0. ,   40. , 5000. , 5000. ,    0. ],
           [   0. , 

### Estudo dos valores do vetor X nas 2 Únicas Iterações da Fase 1 do Simplex para o Problema em Tela

In [47]:
X = list(debug_info['first phase']['first_phase_debug_info'][f'debug_info_iteration_{i:02d}']['x'] for i in range(2))
for x in X:
    display(x)

array([     0.,    600.,      0.,      0.,      0.,      0., 150000.,
       100000.,    600.,      0.,    800.,      0.])

array([     0.,    600.,      0.,      0.,      0.,      0., 132000.,
        76000.,    300.,      0.,    200.,      0.])

### Estudo dos valores do vetor X nas 4 Únicas Iterações da Fase 2 do Simplex para o Problema em Tela

In [50]:
X = list(debug_info['second phase'][f'debug_info_iteration_{i:02d}']['x'] for i in range(4))
for x in X:
    display(x)

array([     0.,    600.,      0.,      0.,      0.,      0., 132000.,
        76000.,    300.,      0.,    200.])

array([     0.,    600.,      0.,      0.,      0.,      0., 132000.,
        76000.,    300.,      0.,    200.])

array([     0.,    600.,      0.,    300.,      0.,      0., 132000.,
        76000.,      0.,      0.,    200.])

array([     1.,    600.,      1.,      1.,      0.,      0., 127500.,
        66000.,      0.,      0.,    200.])

### Estudo dos valores do vetor I nas 4 Únicas Iterações da Fase 2 do Simplex para o Problema em Tela

In [51]:
I = list(debug_info['second phase'][f'debug_info_iteration_{i:02d}']['computed I'] for i in range(4))
for i in I:
    display(i)

array([ 0,  5,  6,  7,  8,  1, 10])

array([ 0,  2,  6,  7,  8,  1, 10])

array([ 0,  2,  6,  7,  3,  1, 10])

array([ 0,  2,  6,  7,  3,  1, 10])