In [2]:
%pip install numpy
%pip install sympy
%load_ext autoreload
%autoreload 2
from simplex_two_phases import simplex as simplex_two_phases
from simplex_tableau import simplex as simplex_tableau
from simplex import simplex
    
import numpy as np
from pprint import pprint

solution_types = {
    -1: 'Unfeasible',
    1: 'Optimal finite solution found',
    2: 'Multiple optimal solutions found',
    3: 'Unbounded'
}

# Lista 5
## Exercício 3.22

In [ ]:
# Instantiate the data for the default minimization
# problem in the form:
# z = min C.T @ X
# subject to:
#     A @ X = B

C = np.array([
    -3,
    -4,
    -2.5,
    0,
    0,
    0
])

A = np.array([
    [3, 4, 2, 1, 0, 0],
    [2, 1, 2, 0, 1, 0],
    [1, 3, 3, 0, 0, 1]
])

B = np.array([
    500,
    400,
    300
])

m, n = A.shape
I = [3, 4, 5]

Z_star, x_I, I_star, A_I, A, iterations, solution_type, debug_info = simplex_two_phases(A, B, C, I, debug = True)
#Z_star, x_star, I_star, iterations, solution_type = simplex(A, b, c, I, debug = True)
x_star = np.zeros(n)
x_star[I_star] = x_I
result_repr = f'''
Exercicio 3.22):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations + 1}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)
display('Simplex Steps:\n\n')
display(debug_info)

## Exercício 3.23

In [24]:
# Instantiate the data for the default minimization
# problem in the form:
# z = min C.T @ X
# subject to:
#     A @ X = B

np.set_printoptions(suppress=True)

C = np.array([
    -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
])

A = np.array([
       [ 1.0e+00,  0.0e+00, -1.0e+00,  0.0e+00,  1.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 1.0e+00,  0.0e+00,  0.0e+00, -1.0e+00,  0.0e+00,  1.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  3.0e+01,  4.5e+03,  0.0e+00,  0.0e+00,  0.0e+00,
         1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  4.0e+01,  5.0e+03,  5.0e+03,  0.0e+00,  0.0e+00,
         0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  5.0e-01,  1.5e+02,  1.5e+02,  0.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00, -1.0e+00,  0.0e+00],
       [ 0.0e+00,  1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,
         0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  1.0e+00]
])

B = np.array([
    0,
    0,
    150e3,
    100e3,
    600,
    600,
    800
])

m, n = A.shape
I = list(range(4,11))

Z_star, x_I, I_star, A_I, A, iterations, solution_type, debug_info = simplex_two_phases(A, B, C, I, debug = True)
#Z_star, x_star, I_star, iterations, solution_type = simplex(A, b, c, I, debug = True)
x_star = np.zeros(n)
x_star[I_star] = x_I
x_star = {
    f'x_{i:}': f'{x:.2f}' for i, x in enumerate(x_star)
}
result_repr = f'''
Exercicio 3.23):

Z_star = {Z_star}
x_star = {str(x_star)}
I_star = {I_star}
iterations = {iterations + 1}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)
display('Simplex Steps:\n\n')
display(debug_info)


Exercicio 3.23):

Z_star = -0.9999999999999993
x_star = {'x_0': '1.00', 'x_1': '600.00', 'x_2': '1.00', 'x_3': '1.00', 'x_4': '0.00', 'x_5': '0.00', 'x_6': '127500.00', 'x_7': '66000.00', 'x_8': '0.00', 'x_9': '0.00', 'x_10': '200.00'}
I_star = [ 0  2  6  7  3  1 10]
iterations = 5
solution_type = 1 - Optimal finite solution found



'Simplex Steps:\n\n'

{'first phase': {'first_phase_debug_info': {'title': 'Simplex method with feasible initial basis for granted',
   'debug_info_iteration_00': {'A_I': array([[1., 0., 0., 0., 0., 0., 0.],
           [0., 1., 0., 0., 0., 0., 0.],
           [0., 0., 1., 0., 0., 0., 0.],
           [0., 0., 0., 1., 0., 0., 0.],
           [0., 0., 0., 0., 1., 0., 0.],
           [0., 0., 0., 0., 0., 1., 0.],
           [0., 0., 0., 0., 0., 0., 1.]]),
    'A_I_inv': array([[1., 0., 0., 0., 0., 0., 0.],
           [0., 1., 0., 0., 0., 0., 0.],
           [0., 0., 1., 0., 0., 0., 0.],
           [0., 0., 0., 1., 0., 0., 0.],
           [0., 0., 0., 0., 1., 0., 0.],
           [0., 0., 0., 0., 0., 1., 0.],
           [0., 0., 0., 0., 0., 0., 1.]]),
    'J': [0, 11, 2, 3, 9],
    'A_J': array([[   1. ,    0. ,   -1. ,    0. ,    0. ],
           [   1. ,    0. ,    0. ,   -1. ,    0. ],
           [   0. ,   30. , 4500. ,    0. ,    0. ],
           [   0. ,   40. , 5000. , 5000. ,    0. ],
           [   0. , 

### Estudo dos valores do vetor X nas 2 Únicas Iterações da Fase 1 do Simplex para o Problema em Tela

In [47]:
X = list(debug_info['first phase']['first_phase_debug_info'][f'debug_info_iteration_{i:02d}']['x'] for i in range(2))
for x in X:
    display(x)

array([     0.,    600.,      0.,      0.,      0.,      0., 150000.,
       100000.,    600.,      0.,    800.,      0.])

array([     0.,    600.,      0.,      0.,      0.,      0., 132000.,
        76000.,    300.,      0.,    200.,      0.])

### Estudo dos valores do vetor X nas 4 Únicas Iterações da Fase 2 do Simplex para o Problema em Tela

In [50]:
X = list(debug_info['second phase'][f'debug_info_iteration_{i:02d}']['x'] for i in range(4))
for x in X:
    display(x)

array([     0.,    600.,      0.,      0.,      0.,      0., 132000.,
        76000.,    300.,      0.,    200.])

array([     0.,    600.,      0.,      0.,      0.,      0., 132000.,
        76000.,    300.,      0.,    200.])

array([     0.,    600.,      0.,    300.,      0.,      0., 132000.,
        76000.,      0.,      0.,    200.])

array([     1.,    600.,      1.,      1.,      0.,      0., 127500.,
        66000.,      0.,      0.,    200.])

### Estudo dos valores do vetor I nas 4 Únicas Iterações da Fase 2 do Simplex para o Problema em Tela

In [51]:
I = list(debug_info['second phase'][f'debug_info_iteration_{i:02d}']['computed I'] for i in range(4))
for i in I:
    display(i)

array([ 0,  5,  6,  7,  8,  1, 10])

array([ 0,  2,  6,  7,  8,  1, 10])

array([ 0,  2,  6,  7,  3,  1, 10])

array([ 0,  2,  6,  7,  3,  1, 10])

## Exercício 3.26

In [16]:
C = np.array([2, -2, -1, 1, 0, 0, 0, 0])
A = np.array([
    [1,  1,  3, -3, 1, 0, 0, 0],
    [-2, 2, -1,  1, 0, 1, 0, 0],
    [2, -2,  3, -3, 0, 0, 1, 0],
    [3, -3, -2,  2, 0, 0, 0, 1]
])
B = np.array([3, 2, 6, 6])

m, n = A.shape
I = list(range(4,8))

Z_star, x_I, I_star, A_I, A, iterations, solution_type, debug_info = simplex_two_phases(A, B, C, I, debug = True)
#Z_star, x_star, I_star, iterations, solution_type = simplex(A, b, c, I, debug = True)
x_star = np.zeros(n)
x_star[I_star] = x_I
x_star = {
    f'x_{i:}': f'{x:.2f}' for i, x in enumerate(x_star)
}
result_repr = f'''
Exercicio 3.26):

Z_star = {Z_star}
x_star = {str(x_star)}
I_star = {I_star}
iterations = {iterations + 1}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)

<class 'NameError'>: name 'np' is not defined

In [51]:
import numpy as np

def find_t_limits(B, b, a_j):
    # Calcula B^-1
    B_inv = np.linalg.inv(B)
    
    # Calcula B^-1 * b e B^-1 * a_j
    B_inv_b = np.dot(B_inv, b)
    B_inv_a_j = np.dot(B_inv, a_j)
    
    # Inicializa os limites
    t_min = -np.inf
    t_max = np.inf
    
    # Itera pelas componentes das desigualdades
    for i in range(len(B_inv_b)):
        if B_inv_a_j[i] > 0:  # Limite superior
            t_max = min(t_max, B_inv_b[i] / B_inv_a_j[i])
        elif B_inv_a_j[i] < 0:  # Limite inferior
            t_min = max(t_min, B_inv_b[i] / B_inv_a_j[i])
        elif B_inv_a_j[i] == 0:  # Caso especial: t não afeta a viabilidade dessa variável
            if B_inv_b[i] < 0:
                # Inviável, sem solução
                return None, None
    
    return t_min, t_max
t_min, t_max = find_t_limits(
    np.linalg.inv(A_I), B, A[:,3]
)
t_min, t_max

(-0.7857142857142857, -1.1999999999999997)

In [73]:
%pip install sympy
from sympy import *
t = symbols('t')
x_star_deg = Matrix(np.linalg.inv(A_I)) * Matrix(B - t * A[:,3])
x_star_deg

Matrix([
[                1.0*t + 0.571428571428572],
[1.28571428571429 - 5.55111512312578e-17*t],
[                         6.85714285714286],
[            11.0 - 4.44089209850063e-16*t]])

In [68]:
x_star = Matrix(np.zeros(A.shape[1]))

In [76]:
for _, i in enumerate(I_star):
    x_star[i] = x_star_deg[_]
x_star[3] = t
x_star
x_1 = np.array(x_star.replace(t, 1e12))
print(x_1)
print(C)
C.dot(x_1)

[[0]
 [1.28565877456305]
 [1000000000000.57]
 [1000000000000.00]
 [0]
 [0]
 [6.85714285714286]
 [10.9995559107901]]
[ 2 -2 -1  1  0  0  0  0]


array([-3.14270019531250], dtype=object)

In [15]:
from IPython.display import display, Markdown
markdown_repr='''

## Iteration 1

Previous Tableau:

|   |\\\\(X_0\\\\) | \\\\(X_1\\\\) | \\\\(X_2\\\\) | \\\\(X_3\\\\) | \\\\(X_4\\\\) | \\\\(X_5\\\\) | \\\\(X_6\\\\) | \\\\(X_7\\\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | -2.000 | 2.000 | 1.000 | -1.000 | 0.000 | 0.000 | 0.000 | 0.000 | 0.000 |
| \\\\(X_4\\\\) | -1.000 | 1.000 | 3.000 | -3.000 | 1.000 | 0.000 | 0.000 | 0.000 | 3.000 |
| \\\\(X_5\\\\) | -2.000 | 2.000 | -1.000 | 1.000 | 0.000 | 1.000 | 0.000 | 0.000 | 2.000 |
| \\\\(X_6\\\\) | 2.000 | -2.000 | 3.000 | -3.000 | 0.000 | 0.000 | 1.000 | 0.000 | 6.000 |
| \\\\(X_7\\\\) | 3.000 | -3.000 | -2.000 | 2.000 | 0.000 | 0.000 | 0.000 | 1.000 | 6.000 |
### Pivot Operations

Variable to enter: \\\\(X_1\\\\)
Variable to leave: \\\\(X_5\\\\)
#### Row Operations:

1. \\\\(R_{X_5} = \\frac{R_{X_5}}{2.0}\\\\)
1. \\\\(R_{C} = R_{C} - 2.0R_{X_5}\\\\)
2. \\\\(R_{X_4} = R_{X_4} - 1.0R_{X_5}\\\\)
3. \\\\(R_{X_6} = R_{X_6} + 2.0R_{X_5}\\\\)
4. \\\\(R_{X_7} = R_{X_7} + 3.0R_{X_5}\\\\)


Computed Tableau:

|   |\\\\(X_0\\\\) | \\\\(X_1\\\\) | \\\\(X_2\\\\) | \\\\(X_3\\\\) | \\\\(X_4\\\\) | \\\\(X_5\\\\) | \\\\(X_6\\\\) | \\\\(X_7\\\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | -1.000 | 0.000 | 0.000 | -2.000 |
| \\\\(X_4\\\\) | 0.000 | 0.000 | 3.500 | -3.500 | 1.000 | -0.500 | 0.000 | 0.000 | 2.000 |
| \\\\(X_1\\\\) | -1.000 | 1.000 | -0.500 | 0.500 | 0.000 | 0.500 | 0.000 | 0.000 | 1.000 |
| \\\\(X_6\\\\) | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | 1.000 | 1.000 | 0.000 | 8.000 |
| \\\\(X_7\\\\) | 0.000 | 0.000 | -3.500 | 3.500 | 0.000 | 1.500 | 0.000 | 1.000 | 9.000 |


## Iteration 2

Previous Tableau:

|   |\\\\(X_0\\\\) | \\\\(X_1\\\\) | \\\\(X_2\\\\) | \\\\(X_3\\\\) | \\\\(X_4\\\\) | \\\\(X_5\\\\) | \\\\(X_6\\\\) | \\\\(X_7\\\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | -1.000 | 0.000 | 0.000 | -2.000 |
| \\\\(X_4\\\\) | 0.000 | 0.000 | 3.500 | -3.500 | 1.000 | -0.500 | 0.000 | 0.000 | 2.000 |
| \\\\(X_1\\\\) | -1.000 | 1.000 | -0.500 | 0.500 | 0.000 | 0.500 | 0.000 | 0.000 | 1.000 |
| \\\\(X_6\\\\) | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | 1.000 | 1.000 | 0.000 | 8.000 |
| \\\\(X_7\\\\) | 0.000 | 0.000 | -3.500 | 3.500 | 0.000 | 1.500 | 0.000 | 1.000 | 9.000 |
### Pivot Operations

Variable to enter: \\\\(X_2\\\\)
Variable to leave: \\\\(X_4\\\\)
#### Row Operations:

1. \\\\(R_{X_4} = \\frac{R_{X_4}}{3.5}\\\\)
1. \\\\(R_{C} = R_{C} - 2.0R_{X_4}\\\\)
2. \\\\(R_{X_1} = R_{X_1} + 0.5R_{X_4}\\\\)
3. \\\\(R_{X_6} = R_{X_6} - 2.0R_{X_4}\\\\)
4. \\\\(R_{X_7} = R_{X_7} + 3.5R_{X_4}\\\\)


Computed Tableau:

|   |\\\\(X_0\\\\) | \\\\(X_1\\\\) | \\\\(X_2\\\\) | \\\\(X_3\\\\) | \\\\(X_4\\\\) | \\\\(X_5\\\\) | \\\\(X_6\\\\) | \\\\(X_7\\\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 0.000 | 0.000 | -0.571 | -0.714 | 0.000 | 0.000 | -3.143 |
| \\\\(X_2\\\\) | 0.000 | 0.000 | 1.000 | -1.000 | 0.286 | -0.143 | 0.000 | 0.000 | 0.571 |
| \\\\(X_1\\\\) | -1.000 | 1.000 | 0.000 | 0.000 | 0.143 | 0.429 | 0.000 | 0.000 | 1.286 |
| \\\\(X_6\\\\) | 0.000 | 0.000 | 0.000 | 0.000 | -0.571 | 1.286 | 1.000 | 0.000 | 6.857 |
| \\\\(X_7\\\\) | 0.000 | 0.000 | 0.000 | 0.000 | 1.000 | 1.000 | 0.000 | 1.000 | 11.000 |

'''
display(Markdown(markdown_repr))



## Iteration 1

Previous Tableau:

|   |\\(X_0\\) | \\(X_1\\) | \\(X_2\\) | \\(X_3\\) | \\(X_4\\) | \\(X_5\\) | \\(X_6\\) | \\(X_7\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | -2.000 | 2.000 | 1.000 | -1.000 | 0.000 | 0.000 | 0.000 | 0.000 | 0.000 |
| \\(X_4\\) | -1.000 | 1.000 | 3.000 | -3.000 | 1.000 | 0.000 | 0.000 | 0.000 | 3.000 |
| \\(X_5\\) | -2.000 | 2.000 | -1.000 | 1.000 | 0.000 | 1.000 | 0.000 | 0.000 | 2.000 |
| \\(X_6\\) | 2.000 | -2.000 | 3.000 | -3.000 | 0.000 | 0.000 | 1.000 | 0.000 | 6.000 |
| \\(X_7\\) | 3.000 | -3.000 | -2.000 | 2.000 | 0.000 | 0.000 | 0.000 | 1.000 | 6.000 |
### Pivot Operations

Variable to enter: \\(X_1\\)
Variable to leave: \\(X_5\\)
#### Row Operations:

1. \\(R_{X_5} = \frac{R_{X_5}}{2.0}\\)
1. \\(R_{C} = R_{C} - 2.0R_{X_5}\\)
2. \\(R_{X_4} = R_{X_4} - 1.0R_{X_5}\\)
3. \\(R_{X_6} = R_{X_6} + 2.0R_{X_5}\\)
4. \\(R_{X_7} = R_{X_7} + 3.0R_{X_5}\\)


Computed Tableau:

|   |\\(X_0\\) | \\(X_1\\) | \\(X_2\\) | \\(X_3\\) | \\(X_4\\) | \\(X_5\\) | \\(X_6\\) | \\(X_7\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | -1.000 | 0.000 | 0.000 | -2.000 |
| \\(X_4\\) | 0.000 | 0.000 | 3.500 | -3.500 | 1.000 | -0.500 | 0.000 | 0.000 | 2.000 |
| \\(X_1\\) | -1.000 | 1.000 | -0.500 | 0.500 | 0.000 | 0.500 | 0.000 | 0.000 | 1.000 |
| \\(X_6\\) | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | 1.000 | 1.000 | 0.000 | 8.000 |
| \\(X_7\\) | 0.000 | 0.000 | -3.500 | 3.500 | 0.000 | 1.500 | 0.000 | 1.000 | 9.000 |


## Iteration 2

Previous Tableau:

|   |\\(X_0\\) | \\(X_1\\) | \\(X_2\\) | \\(X_3\\) | \\(X_4\\) | \\(X_5\\) | \\(X_6\\) | \\(X_7\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | -1.000 | 0.000 | 0.000 | -2.000 |
| \\(X_4\\) | 0.000 | 0.000 | 3.500 | -3.500 | 1.000 | -0.500 | 0.000 | 0.000 | 2.000 |
| \\(X_1\\) | -1.000 | 1.000 | -0.500 | 0.500 | 0.000 | 0.500 | 0.000 | 0.000 | 1.000 |
| \\(X_6\\) | 0.000 | 0.000 | 2.000 | -2.000 | 0.000 | 1.000 | 1.000 | 0.000 | 8.000 |
| \\(X_7\\) | 0.000 | 0.000 | -3.500 | 3.500 | 0.000 | 1.500 | 0.000 | 1.000 | 9.000 |
### Pivot Operations

Variable to enter: \\(X_2\\)
Variable to leave: \\(X_4\\)
#### Row Operations:

1. \\(R_{X_4} = \frac{R_{X_4}}{3.5}\\)
1. \\(R_{C} = R_{C} - 2.0R_{X_4}\\)
2. \\(R_{X_1} = R_{X_1} + 0.5R_{X_4}\\)
3. \\(R_{X_6} = R_{X_6} - 2.0R_{X_4}\\)
4. \\(R_{X_7} = R_{X_7} + 3.5R_{X_4}\\)


Computed Tableau:

|   |\\(X_0\\) | \\(X_1\\) | \\(X_2\\) | \\(X_3\\) | \\(X_4\\) | \\(X_5\\) | \\(X_6\\) | \\(X_7\\) | RHS |
|---|---|---|---|---|---|---|---|---|---|
| Cost | 0.000 | 0.000 | 0.000 | 0.000 | -0.571 | -0.714 | 0.000 | 0.000 | -3.143 |
| \\(X_2\\) | 0.000 | 0.000 | 1.000 | -1.000 | 0.286 | -0.143 | 0.000 | 0.000 | 0.571 |
| \\(X_1\\) | -1.000 | 1.000 | 0.000 | 0.000 | 0.143 | 0.429 | 0.000 | 0.000 | 1.286 |
| \\(X_6\\) | 0.000 | 0.000 | 0.000 | 0.000 | -0.571 | 1.286 | 1.000 | 0.000 | 6.857 |
| \\(X_7\\) | 0.000 | 0.000 | 0.000 | 0.000 | 1.000 | 1.000 | 0.000 | 1.000 | 11.000 |

