In [2]:
%pip install numpy
import simplex
import numpy as np

solution_types = {
    -1: 'Unfeasible',
    1: 'Optimal finite solution found',
    2: 'Multiple optimal solutions found',
    3: 'Unbounded'
}

# letra a
A = np.array([
    [2, 3, 1, 0, 0],
    [2, 1, 0, 1, 0],
    [3, 3, 0, 0, 1]
])
b = np.array([
    18,
    12,
    24
])
c = np.array([
    -5,
    -6,
    0,
    0,
    0
])
I = [2, 3, 4]
Z_star, x_star, I_star, iterations, solution_type = simplex.simplex(A, b, c, I, debug = True)
result_repr = f'''
Letra a):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)

# letra b
A = np.array([
    [1, 3, 1, 0, 0, 0],
    [2, 2, 0, 1, 0, 0],
    [1,-1, 0, 0, 1, 0],
    [0, 1, 0, 0, 0, 1]
])
b = np.array([
    7,
    8,
    -3,
    2
])
c = np.array([
    4,
    -2,
    0,
    0,
    0,
    0
])
I = [2, 3, 4, 5]
Z_star, x_star, I_star, iterations, solution_type = simplex.simplex(A, b, c, I, debug = True)
result_repr = f'''
Letra b):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)

# letra c
A = np.array([
    [-1, -1, 1, 0, 0],
    [-1,  1, 0, 1, 0],
    [ 1,  2, 0, 0, 1]
])
b = np.array([
    -3,
    -1,
    4
])
c = np.array([
    -1,
    -3,
    0,
    0,
    0
])
I = [2, 3, 4]
Z_star, x_star, I_star, iterations, solution_type = simplex.simplex(A, b, c, I, debug = True)
result_repr = f'''
Letra c):

Z_star = {Z_star}
x_star = {x_star}
I_star = {I_star}
iterations = {iterations}
solution_type = {solution_type} - {solution_types[solution_type]}
'''
print(result_repr)

After Iteration 1:
Basic variables indices before: [2 3 4]
Non-basic variables indices before: [0 1]
Basic variables indices after: [1, 3, 4]
Non-basic variables indices after: [0, 2]
x_I = [18. 12. 24.]
A_I =
[[1 0 0]
 [0 1 0]
 [0 0 1]]
A_I^-1 =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A_J =
[[2 1]
 [2 0]
 [3 0]]
π = [0. 0. 0.]
z_0 = 0.0
c_hat_J = [5. 6.]
Variable to enter the basis: x_1
Variable to leave the basis: x_2

After Iteration 2:
Basic variables indices before: [1 3 4]
Non-basic variables indices before: [0 2]
Basic variables indices after: [1, 0, 4]
Non-basic variables indices after: [3, 2]
x_I = [6. 6. 6.]
A_I =
[[3 0 0]
 [1 1 0]
 [3 0 1]]
A_I^-1 =
[[ 0.33333333  0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.          0.          1.        ]]
A_J =
[[0 1]
 [1 0]
 [0 0]]
π = [-2.  0.  0.]
z_0 = -36.0
c_hat_J = [ 1. -2.]
Variable to enter the basis: x_0
Variable to leave the basis: x_3

After Iteration 3:
Basic variables indices before: [1 0 4]
Non-basic va